using System;
using Google.Protobuf.Reflection;

namespace Fenris.Client
{
	// Token: 0x02000113 RID: 275
	public static class SettingsReflection
	{
		// Token: 0x170007B2 RID: 1970
		// (get) Token: 0x06001A1E RID: 6686 RVA: 0x0005D148 File Offset: 0x0005B348
		public static FileDescriptor Descriptor
		{
			get
			{
				return SettingsReflection.descriptor;
			}
		}

		// Token: 0x06001A1F RID: 6687 RVA: 0x0005D160 File Offset: 0x0005B360
		static SettingsReflection()
		{
			byte[] array = Convert.FromBase64String(string.Concat(new string[]
			{
				"Cg5TZXR0aW5ncy5wcm90bxINRmVucmlzLkNsaWVudCJ3Cg1BY3Rpb25CaW5k", "aW5nEhEKBWtleV8xGAEgASgFOgItMRIfChRrZXlfbW9kaWZpZXJfZmxhZ3Nf", "MRgCIAEoDToBMBIRCgVrZXlfMhgDIAEoBToCLTESHwoUa2V5X21vZGlmaWVy", "X2ZsYWdzXzIYBCABKA06ATAiLQoXQ29udHJvbGxlckFjdGlvbkJpbmRpbmcS", "EgoGYnV0dG9uGAEgASgFOgItMSKxEQoYQ29udHJvbGxlckFjdGlvbkJpbmRp", "bmdzElUKJWNvbnRyb2xsZXJfYWN0aW9uX2JpbmRpbmdfZXF1aXBwYWJsZXMY", "ASABKAsyJi5GZW5yaXMuQ2xpZW50LkNvbnRyb2xsZXJBY3Rpb25CaW5kaW5n", "Ek0KHWNvbnRyb2xsZXJfYWN0aW9uX2JpbmRpbmdfbWFwGAIgASgLMiYuRmVu", "cmlzLkNsaWVudC5Db250cm9sbGVyQWN0aW9uQmluZGluZxJRCiFjb250cm9s", "bGVyX2FjdGlvbl9iaW5kaW5nX3ByaW1hcnkYBCABKAsyJi5GZW5yaXMuQ2xp",
				"ZW50LkNvbnRyb2xsZXJBY3Rpb25CaW5kaW5nElMKI2NvbnRyb2xsZXJfYWN0", "aW9uX2JpbmRpbmdfc2Vjb25kYXJ5GAUgASgLMiYuRmVucmlzLkNsaWVudC5D", "b250cm9sbGVyQWN0aW9uQmluZGluZxJRCiFjb250cm9sbGVyX2FjdGlvbl9i", "aW5kaW5nX3NraWxsXzEYBiABKAsyJi5GZW5yaXMuQ2xpZW50LkNvbnRyb2xs", "ZXJBY3Rpb25CaW5kaW5nElEKIWNvbnRyb2xsZXJfYWN0aW9uX2JpbmRpbmdf", "c2tpbGxfMhgHIAEoCzImLkZlbnJpcy5DbGllbnQuQ29udHJvbGxlckFjdGlv", "bkJpbmRpbmcSUQohY29udHJvbGxlcl9hY3Rpb25fYmluZGluZ19za2lsbF8z", "GAggASgLMiYuRmVucmlzLkNsaWVudC5Db250cm9sbGVyQWN0aW9uQmluZGlu", "ZxJRCiFjb250cm9sbGVyX2FjdGlvbl9iaW5kaW5nX3NraWxsXzQYCSABKAsy", "Ji5GZW5yaXMuQ2xpZW50LkNvbnRyb2xsZXJBY3Rpb25CaW5kaW5nElIKImNv",
				"bnRyb2xsZXJfYWN0aW9uX2JpbmRpbmdfdXNlX2l0ZW0YCiABKAsyJi5GZW5y", "aXMuQ2xpZW50LkNvbnRyb2xsZXJBY3Rpb25CaW5kaW5nElUKJWNvbnRyb2xs", "ZXJfYWN0aW9uX2JpbmRpbmdfdGFyZ2V0X2xvY2sYCyABKAsyJi5GZW5yaXMu", "Q2xpZW50LkNvbnRyb2xsZXJBY3Rpb25CaW5kaW5nEloKKmNvbnRyb2xsZXJf", "YWN0aW9uX2JpbmRpbmdfc2hvd19pdGVtX2xhYmVscxgMIAEoCzImLkZlbnJp", "cy5DbGllbnQuQ29udHJvbGxlckFjdGlvbkJpbmRpbmcSWAooY29udHJvbGxl", "cl9hY3Rpb25fYmluZGluZ19xdWlja19yZXNwb25zZRgNIAEoCzImLkZlbnJp", "cy5DbGllbnQuQ29udHJvbGxlckFjdGlvbkJpbmRpbmcSTwofY29udHJvbGxl", "cl9hY3Rpb25fYmluZGluZ193aGVlbBgOIAEoCzImLkZlbnJpcy5DbGllbnQu", "Q29udHJvbGxlckFjdGlvbkJpbmRpbmcSVgomY29udHJvbGxlcl9hY3Rpb25f",
				"YmluZGluZ19wdXNoX3RvX3RhbGsYDyABKAsyJi5GZW5yaXMuQ2xpZW50LkNv", "bnRyb2xsZXJBY3Rpb25CaW5kaW5nEk8KH2NvbnRyb2xsZXJfYWN0aW9uX2Jp", "bmRpbmdfZXZhZGUYECABKAsyJi5GZW5yaXMuQ2xpZW50LkNvbnRyb2xsZXJB", "Y3Rpb25CaW5kaW5nElIKImNvbnRyb2xsZXJfYWN0aW9uX2JpbmRpbmdfaW50", "ZXJhY3QYESABKAsyJi5GZW5yaXMuQ2xpZW50LkNvbnRyb2xsZXJBY3Rpb25C", "aW5kaW5nEl0KLWNvbnRyb2xsZXJfYWN0aW9uX2JpbmRpbmdfd2hlZWxfcGFn", "ZV9iYWNrd2FyZBgSIAEoCzImLkZlbnJpcy5DbGllbnQuQ29udHJvbGxlckFj", "dGlvbkJpbmRpbmcSXAosY29udHJvbGxlcl9hY3Rpb25fYmluZGluZ193aGVl", "bF9wYWdlX2ZvcndhcmQYEyABKAsyJi5GZW5yaXMuQ2xpZW50LkNvbnRyb2xs", "ZXJBY3Rpb25CaW5kaW5nElsKK2NvbnRyb2xsZXJfYWN0aW9uX2JpbmRpbmdf",
				"Y29tYmluZWRfaW50ZXJhY3QYFCABKAsyJi5GZW5yaXMuQ2xpZW50LkNvbnRy", "b2xsZXJBY3Rpb25CaW5kaW5nElsKK2NvbnRyb2xsZXJfYWN0aW9uX2JpbmRp", "bmdfY3ljbGVfdGFyZ2V0X2xvY2sYFSABKAsyJi5GZW5yaXMuQ2xpZW50LkNv", "bnRyb2xsZXJBY3Rpb25CaW5kaW5nElUKJWNvbnRyb2xsZXJfYWN0aW9uX2Jp", "bmRpbmdfdG93bl9wb3J0YWwYFiABKAsyJi5GZW5yaXMuQ2xpZW50LkNvbnRy", "b2xsZXJBY3Rpb25CaW5kaW5nEmIKMmNvbnRyb2xsZXJfYWN0aW9uX2JpbmRp", "bmdfam9pbl9zcGVlY2hfdG9fdGV4dF9jaGF0GBcgASgLMiYuRmVucmlzLkNs", "aWVudC5Db250cm9sbGVyQWN0aW9uQmluZGluZxJkCjRjb250cm9sbGVyX2Fj", "dGlvbl9iaW5kaW5nX3R0c19za2lwX2N1cnJlbnRfdXR0ZXJhbmNlGBggASgL", "MiYuRmVucmlzLkNsaWVudC5Db250cm9sbGVyQWN0aW9uQmluZGluZxJjCjNj",
				"b250cm9sbGVyX2FjdGlvbl9iaW5kaW5nX3R0c19jYW5jZWxfYWxsX3V0dGVy", "YW5jZXMYGSABKAsyJi5GZW5yaXMuQ2xpZW50LkNvbnRyb2xsZXJBY3Rpb25C", "aW5kaW5nEk8KH2NvbnRyb2xsZXJfYWN0aW9uX2JpbmRpbmdfbW91bnQYGiAB", "KAsyJi5GZW5yaXMuQ2xpZW50LkNvbnRyb2xsZXJBY3Rpb25CaW5kaW5nIlEK", "ElNvY2lhbFdoZWVsQmluZGluZxIMCgRzbG90GAEgASgFEi0KB2JpbmRpbmcY", "AiABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmciPgoRRm9udENv", "bG9yT3ZlcnJpZGUSFwoPZm9udF9jb2xvcl9oYXNoGAEgASgNEhAKCHVpX2Nv", "bG9yGAIgASgPIscCChNHYW1lQWNjb3VudFNldHRpbmdzEhcKD2hlcm9fbGlz", "dF9vcmRlchgBIAMoDBI+ChRmb250X2NvbG9yX292ZXJyaWRlcxgCIAMoCzIg", "LkZlbnJpcy5DbGllbnQuRm9udENvbG9yT3ZlcnJpZGUSLwonY2xhbl9uZXdf",
				"aW52aXRlc19hcHBsaWNhdGlvbnNfdGltZXN0YW1wGAUgASgEEhEKCXNlZW5f", "bmV3cxgGIAMoCRINCgVmbGFncxgHIAEoDRIYChBzZWVuX3Byb2R1Y3RfaWRz", "GAggAygEEiAKGHNlZW5fcmVjZW50X3B1cmNoYXNlX2lkcxgJIAMoBSJICgVG", "bGFncxIfChtDQU1QQUlHTl9TS0lQX1RVVE9SSUFMX1NFRU4QARIeChpTVE9S", "RV9SRUZSRVNIRURfSU5UUk9fU0VFThACIv46CgtQcmVmZXJlbmNlcxIPCgd2", "ZXJzaW9uGAEgASgFEhAKBWZsYWdzGAIgASgNOgEwEi0KImRlcHJlY2F0ZWRf", "aXRlbXNfb25fZ3JvdW5kX3NldHRpbmcYAyABKA06ATASPQoXYWN0aW9uX2Jp", "bmRpbmdfaGlyZWxpbmcYBSABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJp", "bmRpbmcSOwoVYWN0aW9uX2JpbmRpbmdfc2tpbGxzGAYgASgLMhwuRmVucmlz", "LkNsaWVudC5BY3Rpb25CaW5kaW5nElAKKmFjdGlvbl9iaW5kaW5nX2FjY2Vw",
				"dF9wYXJ0eV9pbnZpdGVfcmVxdWVzdBgHIAEoCzIcLkZlbnJpcy5DbGllbnQu", "QWN0aW9uQmluZGluZxI5ChNhY3Rpb25fYmluZGluZ19sb3JlGAggASgLMhwu", "RmVucmlzLkNsaWVudC5BY3Rpb25CaW5kaW5nEjsKFWFjdGlvbl9iaW5kaW5n", "X3NvY2lhbBgJIAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxI5", "ChNhY3Rpb25fYmluZGluZ19oZWxwGAsgASgLMhwuRmVucmlzLkNsaWVudC5B", "Y3Rpb25CaW5kaW5nEkIKHGFjdGlvbl9iaW5kaW5nX3JlY2VudHBsYXllcnMY", "DCABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmcSPgoYYWN0aW9u", "X2JpbmRpbmdfY2hhdGxvYmJ5GA0gASgLMhwuRmVucmlzLkNsaWVudC5BY3Rp", "b25CaW5kaW5nEkEKG2FjdGlvbl9iaW5kaW5nX2FjaGlldmVtZW50cxgOIAEo", "CzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxI8ChZhY3Rpb25fYmlu",
				"ZGluZ19wcm9maWxlGA8gASgLMhwuRmVucmlzLkNsaWVudC5BY3Rpb25CaW5k", "aW5nEkAKGmFjdGlvbl9iaW5kaW5nX2VxdWlwcGFibGVzGBAgASgLMhwuRmVu", "cmlzLkNsaWVudC5BY3Rpb25CaW5kaW5nEjwKFmFjdGlvbl9iaW5kaW5nX2Nv", "bnNvbGUYEiABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmcSOAoS", "YWN0aW9uX2JpbmRpbmdfbWFwGBMgASgLMhwuRmVucmlzLkNsaWVudC5BY3Rp", "b25CaW5kaW5nEj8KGWFjdGlvbl9iaW5kaW5nX3NraWxsX3RyZWUYFCABKAsy", "HC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmcSRwohYWN0aW9uX2JpbmRp", "bmdfdG9nZ2xlcGxheWVyaHBiYXJzGBYgASgLMhwuRmVucmlzLkNsaWVudC5B", "Y3Rpb25CaW5kaW5nEkgKImFjdGlvbl9iaW5kaW5nX3RvZ2dsZWRhbWFnZW51", "bWJlcnMYFyABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmcSSAoi",
				"YWN0aW9uX2JpbmRpbmdfdG9nZ2xlaXRlbXNvbmdyb3VuZBgYIAEoCzIcLkZl", "bnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxI+ChhhY3Rpb25fYmluZGluZ19y", "ZXdoaXNwZXIYGSABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmcS", "QQobYWN0aW9uX2JpbmRpbmdfd2hpc3BlcnJlcGx5GBogASgLMhwuRmVucmlz", "LkNsaWVudC5BY3Rpb25CaW5kaW5nEj0KF2FjdGlvbl9iaW5kaW5nX3ZvaWNl", "cHR0GBsgASgLMhwuRmVucmlzLkNsaWVudC5BY3Rpb25CaW5kaW5nEkAKGmFj", "dGlvbl9iaW5kaW5nX3NvY2lhbHdoZWVsGBwgASgLMhwuRmVucmlzLkNsaWVu", "dC5BY3Rpb25CaW5kaW5nEkMKHWFjdGlvbl9iaW5kaW5nX2Zhc3RxdWVzdHRy", "YWNrGB0gASgLMhwuRmVucmlzLkNsaWVudC5BY3Rpb25CaW5kaW5nEkoKJGFj", "dGlvbl9iaW5kaW5nX3RvZ2dsZV9sZmRfY29tcGFuaW9ucxgeIAEoCzIcLkZl",
				"bnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxJAChphY3Rpb25fYmluZGluZ19j", "b2xsZWN0aW9ucxgfIAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGlu", "ZxJKCh9hY3Rpb25fYmluZGluZ19zb2NpYWx3aGVlbF9sZWZ0GCAgAygLMiEu", "RmVucmlzLkNsaWVudC5Tb2NpYWxXaGVlbEJpbmRpbmcSTAohYWN0aW9uX2Jp", "bmRpbmdfc29jaWFsd2hlZWxfbWlkZGxlGCEgAygLMiEuRmVucmlzLkNsaWVu", "dC5Tb2NpYWxXaGVlbEJpbmRpbmcSSwogYWN0aW9uX2JpbmRpbmdfc29jaWFs", "d2hlZWxfcmlnaHQYIiADKAsyIS5GZW5yaXMuQ2xpZW50LlNvY2lhbFdoZWVs", "QmluZGluZxJOCihhY3Rpb25fYmluZGluZ19zb2NpYWx3aGVlbF9wYWdlX2Jh", "Y2t3YXJkGCMgASgLMhwuRmVucmlzLkNsaWVudC5BY3Rpb25CaW5kaW5nEk0K", "J2FjdGlvbl9iaW5kaW5nX3NvY2lhbHdoZWVsX3BhZ2VfZm9yd2FyZBgkIAEo",
				"CzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxI+ChhhY3Rpb25fYmlu", "ZGluZ19hYmlsaXRpZXMYJSABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJp", "bmRpbmcSPwoZYWN0aW9uX2JpbmRpbmdfcmVwb3J0X2J1ZxgmIAEoCzIcLkZl", "bnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxJDCh1hY3Rpb25fYmluZGluZ19y", "ZXBvcnRfY29udGVudBgnIAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmlu", "ZGluZxJNCidhY3Rpb25fYmluZGluZ19qb2luX3NwZWVjaF90b190ZXh0X2No", "YXQYKCABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmcSTwopYWN0", "aW9uX2JpbmRpbmdfdHRzX3NraXBfY3VycmVudF91dHRlcmFuY2UYKSABKAsy", "HC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmcSTgooYWN0aW9uX2JpbmRp", "bmdfdHRzX2NhbmNlbF9hbGxfdXR0ZXJhbmNlcxgqIAEoCzIcLkZlbnJpcy5D",
				"bGllbnQuQWN0aW9uQmluZGluZxJMCiZhY3Rpb25fYmluZGluZ19zY3JlZW5f", "cmVhZGVyX3NraXBfbGluZRgrIAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0aW9u", "QmluZGluZxI6ChRhY3Rpb25fYmluZGluZ19zdG9yZRgsIAEoCzIcLkZlbnJp", "cy5DbGllbnQuQWN0aW9uQmluZGluZxI/ChlhY3Rpb25fYmluZGluZ19tb3Vu", "dF9zcHVyGC0gASgLMhwuRmVucmlzLkNsaWVudC5BY3Rpb25CaW5kaW5nEkMK", "HWFjdGlvbl9iaW5kaW5nX21vdW50X2Rpc21vdW50GC4gASgLMhwuRmVucmlz", "LkNsaWVudC5BY3Rpb25CaW5kaW5nEkoKJGFjdGlvbl9iaW5kaW5nX21vdW50", "X2NvbWJhdF9kaXNtb3VudBgvIAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0aW9u", "QmluZGluZxJAChphY3Rpb25fYmluZGluZ190b2dnbGVfem9vbRgwIAEoCzIc", "LkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxJBChthY3Rpb25fYmluZGlu",
				"Z19ob2xkcG9zaXRpb24YNSABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJp", "bmRpbmcSSQojYWN0aW9uX2JpbmRpbmdfc3lzdGVtbWFzdGVydm9sdW1ldXAY", "NiABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmcSSwolYWN0aW9u", "X2JpbmRpbmdfc3lzdGVtbWFzdGVydm9sdW1lZG93bhg3IAEoCzIcLkZlbnJp", "cy5DbGllbnQuQWN0aW9uQmluZGluZxJGCiBhY3Rpb25fYmluZGluZ19zeXN0", "ZW10b2dnbGVtdXNpYxg4IAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmlu", "ZGluZxJGCiBhY3Rpb25fYmluZGluZ19zeXN0ZW10b2dnbGVzb3VuZBg5IAEo", "CzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxJFCh9hY3Rpb25fYmlu", "ZGluZ19zeXN0ZW1zY3JlZW5zaG90GDogASgLMhwuRmVucmlzLkNsaWVudC5B", "Y3Rpb25CaW5kaW5nEkQKHmFjdGlvbl9iaW5kaW5nX3N5c3RlbXRvZ2dsZWZw",
				"cxhAIAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxI/ChlhY3Rp", "b25fYmluZGluZ19jaGF0cGFnZXVwGEEgASgLMhwuRmVucmlzLkNsaWVudC5B", "Y3Rpb25CaW5kaW5nEkEKG2FjdGlvbl9iaW5kaW5nX2NoYXRwYWdlZG93bhhC", "IAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxI7ChVhY3Rpb25f", "YmluZGluZ19ncm91cHMYQyABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJp", "bmRpbmcSOQoTYWN0aW9uX2JpbmRpbmdfY2xhbhhEIAEoCzIcLkZlbnJpcy5D", "bGllbnQuQWN0aW9uQmluZGluZxJDCh1hY3Rpb25fYmluZGluZ19jaGF0X25l", "eHRfdmlldxhGIAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxJH", "CiFhY3Rpb25fYmluZGluZ19jaGF0X3ByZXZpb3VzX3ZpZXcYRyABKAsyHC5G", "ZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmcSQQobYWN0aW9uX2JpbmRpbmdf",
				"bGVhZGVyYm9hcmRzGEggASgLMhwuRmVucmlzLkNsaWVudC5BY3Rpb25CaW5k", "aW5nEkQKHmFjdGlvbl9iaW5kaW5nX2NoYXRfcmVzZXRfZmFkZRhJIAEoCzIc", "LkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxI7ChVhY3Rpb25fYmluZGlu", "Z19xdWVzdHMYSiABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmcS", "QgocYWN0aW9uX2JpbmRpbmdfcXVlc3RzX3RvZ2dsZRhLIAEoCzIcLkZlbnJp", "cy5DbGllbnQuQWN0aW9uQmluZGluZxI4ChJhY3Rpb25fYmluZGluZ19ydW4Y", "TyABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmcSPQoXYWN0aW9u", "X2JpbmRpbmdfaW50ZXJhY3QYUCABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlv", "bkJpbmRpbmcSPAoWYWN0aW9uX2JpbmRpbmdfcHJpbWFyeRhRIAEoCzIcLkZl", "bnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxI+ChhhY3Rpb25fYmluZGluZ19z",
				"ZWNvbmRhcnkYUiABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJpbmRpbmcS", "PAoWYWN0aW9uX2JpbmRpbmdfc2tpbGxfMRhTIAEoCzIcLkZlbnJpcy5DbGll", "bnQuQWN0aW9uQmluZGluZxI8ChZhY3Rpb25fYmluZGluZ19za2lsbF8yGFQg", "ASgLMhwuRmVucmlzLkNsaWVudC5BY3Rpb25CaW5kaW5nEjwKFmFjdGlvbl9i", "aW5kaW5nX3NraWxsXzMYVSABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJp", "bmRpbmcSPAoWYWN0aW9uX2JpbmRpbmdfc2tpbGxfNBhWIAEoCzIcLkZlbnJp", "cy5DbGllbnQuQWN0aW9uQmluZGluZxI6ChRhY3Rpb25fYmluZGluZ19tb3Vu", "dBhXIAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxI6ChRhY3Rp", "b25fYmluZGluZ19ldmFkZRhYIAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0aW9u", "QmluZGluZxI9ChdhY3Rpb25fYmluZGluZ191c2VfaXRlbRhZIAEoCzIcLkZl",
				"bnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxJCChxhY3Rpb25fYmluZGluZ19j", "ZW50ZXJfY2FtZXJhGFogASgLMhwuRmVucmlzLkNsaWVudC5BY3Rpb25CaW5k", "aW5nEkEKG2FjdGlvbl9iaW5kaW5nX2RlYnVnX2NhbWVyYRhbIAEoCzIcLkZl", "bnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxJECh5hY3Rpb25fYmluZGluZ19z", "b2NpYWxfaW50ZXJhY3QYXSABKAsyHC5GZW5yaXMuQ2xpZW50LkFjdGlvbkJp", "bmRpbmcSSAoiYWN0aW9uX2JpbmRpbmdfYWNjZXB0X3BhcnR5X2ludml0ZRhe", "IAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxJAChphY3Rpb25f", "YmluZGluZ19sb2NrX3RhcmdldBhfIAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0", "aW9uQmluZGluZxJAChphY3Rpb25fYmluZGluZ190b3duX3BvcnRhbBhgIAEo", "CzIcLkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxI/ChlhY3Rpb25fYmlu",
				"ZGluZ19mb3JjZV9tb3ZlGGEgASgLMhwuRmVucmlzLkNsaWVudC5BY3Rpb25C", "aW5kaW5nEkEKG2FjdGlvbl9iaW5kaW5nX2NsYXNzX3NjcmVlbhhiIAEoCzIc", "LkZlbnJpcy5DbGllbnQuQWN0aW9uQmluZGluZxJGCiBhY3Rpb25fYmluZGlu", "Z19jeWNsZV9sb2NrX3RhcmdldBhjIAEoCzIcLkZlbnJpcy5DbGllbnQuQWN0", "aW9uQmluZGluZxIaCg9ub3RpZnlfZHVyYXRpb24YZCABKA06ATASHQoSa2V5", "YmluZGluZ192ZXJzaW9uGGUgASgNOgEwEhIKBmZsYWdzMhjIASABKA06ATAS", "GwoOY29udHJvbF9zY2hlbWUYzQEgASgPOgItMRItCiFjb250cm9sbGVyX2J1", "dHRvbl9iaW5kaW5nX3ZlcnNpb24YzgEgASgNOgEwEkwKGmNvbnRyb2xsZXJf", "YmluZGluZ3NfeGlucHV0GM8BIAEoCzInLkZlbnJpcy5DbGllbnQuQ29udHJv", "bGxlckFjdGlvbkJpbmRpbmdzEkkKF2NvbnRyb2xsZXJfYmluZGluZ3NfcHM0",
				"GNABIAEoCzInLkZlbnJpcy5DbGllbnQuQ29udHJvbGxlckFjdGlvbkJpbmRp", "bmdzEkoKGGNvbnRyb2xsZXJfYmluZGluZ3Nfbng2NBjRASABKAsyJy5GZW5y", "aXMuQ2xpZW50LkNvbnRyb2xsZXJBY3Rpb25CaW5kaW5ncxIsCiNjaGF0X2Jh", "Y2tncm91bmRfb3BhY2l0eV93aGVuX2FjdGl2ZRjSASABKA0SHgoVY2hhdF90", "aW1lc3RhbXBfZm9ybWF0GNMBIAEoDRInChtpdGVtX2xhYmVsX29uX2Ryb3Bf", "ZHVyYXRpb24Y1AEgASgNOgEwEiMKF2l0ZW1fbGFiZWxfZGlzcGxheV9tb2Rl", "GNUBIAEoDToBMBIrCh1jb250cm9sbGVyX2N1cnNvcl9zZW5zaXRpdml0eRjW", "ASABKAI6AzAuNBIoChpjb250cm9sbGVyX2lubmVyX2RlYWRfem9uZRjXASAB", "KAI6AzAuNRImChpjb250cm9sbGVyX291dGVyX2RlYWRfem9uZRjYASABKAI6", "ATASHQoRcG93ZXJfdG9nZ2xlX21vZGUY2QEgASgNOgEwEikKHXNvY2lhbF93",
				"aGVlbF9hY3RpdmF0aW9uX3N0eWxlGNoBIAEoDToBMBIjChdtb25zdGVyX2hl", "YWx0aF9iYXJfbW9kZRjbASABKA06ATASJAoYaG9sZF9wb3NpdGlvbl9pbnB1", "dF9tb2RlGNwBIAEoDToBMBJJChdjb250cm9sbGVyX2JpbmRpbmdzX3BzNRjd", "ASABKAsyJy5GZW5yaXMuQ2xpZW50LkNvbnRyb2xsZXJBY3Rpb25CaW5kaW5n", "cyKOBgoFRmxhZ3MSFwoTU0hPV19QTEFZRVJfSFBfQkFSUxACEhcKE1NIT1df", "REFNQUdFX05VTUJFUlMQAxIUChBBVVRPX0VRVUlQX0lURU1TEAQSEgoOU0hP", "V19UVVRPUklBTFMQBRIYChROT1RJRllfRlJJRU5EX09OTElORRAHEhkKFU5P", "VElGWV9GUklFTkRfT0ZGTElORRAIEhkKFU5PVElGWV9GUklFTkRfUkVRVUVT", "VBAJEh0KGU5PVElGWV9GUklFTkRfQUNISUVWRU1FTlQQChIZChVOT1RJRllf", "RElTUExBWV9XSU5ET1cQCxIaChZNQVRVUkVfTEFOR1VBR0VfRklMVEVSEAwS",
				"FAoQQUxMT1dfUVVJQ0tfSk9JThANEh0KGUVDSE9fUVVFU1RfRElBTE9HX1RP", "X0NIQVQQDhIYChRESVNBQkxFX1NDUkVFTl9TSEFLRRAPEhcKE1VTRV9MRUZU", "X0hVRF9DT05GSUcQEBIgChxESVNBQkxFX0NPTlRST0xMRVJfVklCUkFUSU9O", "EBESHQoZTk9USUZZX0NMQU5fTUVNQkVSX09OTElORRASEhUKEUNST1NTUExB", "WV9FTkFCTEVEEBMSFgoSQ1JPU1NDT01NU19FTkFCTEVEEBQSHAoYRElTQUJM", "RV9DT01CQVRfSElUX0ZMQVNIEBUSIwofU1FVRUxDSF9DTEFOX05FV1NfTk9U", "SUZJQ0FUSU9OUxAWEhMKD1JFRFVDRV9TVFJPQklORxAXEiIKHlBMQVlfU09V", "TkRfT05fV0hJU1BFUl9SRUNFSVZFRBAYEhsKF0pPSU5fTE9DQUxfQ0hBVF9D", "SEFOTkVMEBoSGwoXSk9JTl9UUkFERV9DSEFUX0NIQU5ORUwQGxIcChhTSE9X", "X0xPQ0FMX0NIQVRfQkFMTE9PTlMQHBIcChhTSE9XX1BBUlRZX0NIQVRfQkFM",
				"TE9PTlMQHRIbChdTSE9XX0NMQU5fQ0hBVF9CQUxMT09OUxAeEhwKGFNIT1df", "VFJBREVfQ0hBVF9CQUxMT09OUxAfIugDCgZGbGFnczISFQoRRElTQUJMRV9D", "VVRTQ0VORVMQAxIVChFTSE9XX0xPQ0FMUExBWUVSUxAFEicKI05PVElGWV9H", "VUlMRF9NRU1CRVJfT05MSU5FX0RJU0FCTEVEEAYSFAoQQURWQU5DRURfQ09N", "UEFSRRAHEhkKFUFEVkFOQ0VEX1RPT0xUSVBfSU5GTxAIEh0KGURJU0FCTEVf", "Q09NQklORURfSU5URVJBQ1QQCRIXChNIT0xEX1RPX0xPQ0tfVEFSR0VUEAoS", "GwoXQVVUT19QUk9HUkVTU0lOR19ESUFMT0cQCxIXChNTSE9XX01JTklPTl9I", "UF9CQVJTEAwSJwojRklSU1RfVElNRV9PUFRJT05fU0VUVElOR19DT01QTEVU", "RUQQDRIiCh5GSVJTVF9DSEFSQUNURVJfRkxPV19DT01QTEVURUQQDhIXChNQ", "RVJTSVNUX1RBUkdFVF9MT0NLEBASGgoWU1dBUF9DT05UUk9MTEVSX1NUSUNL",
				"UxAREhoKFk9DQ0xVU0lPTl9ISUdITElHSFRJTkcQEhIXChNQTEFZRVJfSElH", "SExJR0hUSU5HEBMSGwoXQ09NQklORV9QUklNQVJZX0FDVElPTlMQFBIUChBN", "T1VTRV9XSEVFTF9aT09NEBU="
			}));
			SettingsReflection.descriptor = FileDescriptor.FromGeneratedCode(array, new FileDescriptor[0], new GeneratedClrTypeInfo(null, null, new GeneratedClrTypeInfo[]
			{
				new GeneratedClrTypeInfo(typeof(ActionBinding), ActionBinding.Parser, new string[] { "Key1", "KeyModifierFlags1", "Key2", "KeyModifierFlags2" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(ControllerActionBinding), ControllerActionBinding.Parser, new string[] { "Button" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(ControllerActionBindings), ControllerActionBindings.Parser, new string[]
				{
					"ControllerActionBindingEquippables", "ControllerActionBindingMap", "ControllerActionBindingPrimary", "ControllerActionBindingSecondary", "ControllerActionBindingSkill1", "ControllerActionBindingSkill2", "ControllerActionBindingSkill3", "ControllerActionBindingSkill4", "ControllerActionBindingUseItem", "ControllerActionBindingTargetLock",
					"ControllerActionBindingShowItemLabels", "ControllerActionBindingQuickResponse", "ControllerActionBindingWheel", "ControllerActionBindingPushToTalk", "ControllerActionBindingEvade", "ControllerActionBindingInteract", "ControllerActionBindingWheelPageBackward", "ControllerActionBindingWheelPageForward", "ControllerActionBindingCombinedInteract", "ControllerActionBindingCycleTargetLock",
					"ControllerActionBindingTownPortal", "ControllerActionBindingJoinSpeechToTextChat", "ControllerActionBindingTtsSkipCurrentUtterance", "ControllerActionBindingTtsCancelAllUtterances", "ControllerActionBindingMount"
				}, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(SocialWheelBinding), SocialWheelBinding.Parser, new string[] { "Slot", "Binding" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(FontColorOverride), FontColorOverride.Parser, new string[] { "FontColorHash", "UiColor" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(GameAccountSettings), GameAccountSettings.Parser, new string[] { "HeroListOrder", "FontColorOverrides", "ClanNewInvitesApplicationsTimestamp", "SeenNews", "Flags", "SeenProductIds", "SeenRecentPurchaseIds" }, null, new Type[] { typeof(GameAccountSettings.Types.Flags) }, null, null),
				new GeneratedClrTypeInfo(typeof(Preferences), Preferences.Parser, new string[]
				{
					"Version", "Flags", "DeprecatedItemsOnGroundSetting", "ActionBindingHireling", "ActionBindingSkills", "ActionBindingAcceptPartyInviteRequest", "ActionBindingLore", "ActionBindingSocial", "ActionBindingHelp", "ActionBindingRecentplayers",
					"ActionBindingChatlobby", "ActionBindingAchievements", "ActionBindingProfile", "ActionBindingEquippables", "ActionBindingConsole", "ActionBindingMap", "ActionBindingSkillTree", "ActionBindingToggleplayerhpbars", "ActionBindingToggledamagenumbers", "ActionBindingToggleitemsonground",
					"ActionBindingRewhisper", "ActionBindingWhisperreply", "ActionBindingVoiceptt", "ActionBindingSocialwheel", "ActionBindingFastquesttrack", "ActionBindingToggleLfdCompanions", "ActionBindingCollections", "ActionBindingSocialwheelLeft", "ActionBindingSocialwheelMiddle", "ActionBindingSocialwheelRight",
					"ActionBindingSocialwheelPageBackward", "ActionBindingSocialwheelPageForward", "ActionBindingAbilities", "ActionBindingReportBug", "ActionBindingReportContent", "ActionBindingJoinSpeechToTextChat", "ActionBindingTtsSkipCurrentUtterance", "ActionBindingTtsCancelAllUtterances", "ActionBindingScreenReaderSkipLine", "ActionBindingStore",
					"ActionBindingMountSpur", "ActionBindingMountDismount", "ActionBindingMountCombatDismount", "ActionBindingToggleZoom", "ActionBindingHoldposition", "ActionBindingSystemmastervolumeup", "ActionBindingSystemmastervolumedown", "ActionBindingSystemtogglemusic", "ActionBindingSystemtogglesound", "ActionBindingSystemscreenshot",
					"ActionBindingSystemtogglefps", "ActionBindingChatpageup", "ActionBindingChatpagedown", "ActionBindingGroups", "ActionBindingClan", "ActionBindingChatNextView", "ActionBindingChatPreviousView", "ActionBindingLeaderboards", "ActionBindingChatResetFade", "ActionBindingQuests",
					"ActionBindingQuestsToggle", "ActionBindingRun", "ActionBindingInteract", "ActionBindingPrimary", "ActionBindingSecondary", "ActionBindingSkill1", "ActionBindingSkill2", "ActionBindingSkill3", "ActionBindingSkill4", "ActionBindingMount",
					"ActionBindingEvade", "ActionBindingUseItem", "ActionBindingCenterCamera", "ActionBindingDebugCamera", "ActionBindingSocialInteract", "ActionBindingAcceptPartyInvite", "ActionBindingLockTarget", "ActionBindingTownPortal", "ActionBindingForceMove", "ActionBindingClassScreen",
					"ActionBindingCycleLockTarget", "NotifyDuration", "KeybindingVersion", "Flags2", "ControlScheme", "ControllerButtonBindingVersion", "ControllerBindingsXinput", "ControllerBindingsPs4", "ControllerBindingsNx64", "ChatBackgroundOpacityWhenActive",
					"ChatTimestampFormat", "ItemLabelOnDropDuration", "ItemLabelDisplayMode", "ControllerCursorSensitivity", "ControllerInnerDeadZone", "ControllerOuterDeadZone", "PowerToggleMode", "SocialWheelActivationStyle", "MonsterHealthBarMode", "HoldPositionInputMode",
					"ControllerBindingsPs5"
				}, null, new Type[]
				{
					typeof(Preferences.Types.Flags),
					typeof(Preferences.Types.Flags2)
				}, null, null)
			}));
		}

		// Token: 0x04000A70 RID: 2672
		private static FileDescriptor descriptor;
	}
}
