using System;
using Google.Protobuf.Reflection;

namespace Bgs.Protocol.Channel.V2
{
	// Token: 0x0200065B RID: 1627
	public static class ChannelServiceReflection
	{
		// Token: 0x17002F24 RID: 12068
		// (get) Token: 0x06009725 RID: 38693 RVA: 0x00248C34 File Offset: 0x00246E34
		public static FileDescriptor Descriptor
		{
			get
			{
				return ChannelServiceReflection.descriptor;
			}
		}

		// Token: 0x06009726 RID: 38694 RVA: 0x00248C4C File Offset: 0x00246E4C
		static ChannelServiceReflection()
		{
			byte[] array = Convert.FromBase64String(string.Concat(new string[]
			{
				"CjViZ3MvbG93L3BiL2NsaWVudC9hcGkvY2xpZW50L3YyL2NoYW5uZWxfc2Vy", "dmljZS5wcm90bxIXYmdzLnByb3RvY29sLmNoYW5uZWwudjIaM2Jncy9sb3cv", "cGIvY2xpZW50L2FwaS9jbGllbnQvdjIvY2hhbm5lbF90eXBlcy5wcm90bxoh", "YmdzL2xvdy9wYi9jbGllbnQvcnBjX3R5cGVzLnByb3RvGiViZ3MvbG93L3Bi", "L2NsaWVudC9tZXNzYWdlX3R5cGVzLnByb3RvGihiZ3MvbG93L3BiL2NsaWVu", "dC9pbnZpdGF0aW9uX3R5cGVzLnByb3RvGiNiZ3MvbG93L3BiL2NsaWVudC92", "b2ljZV90eXBlcy5wcm90byKUAQoUQ3JlYXRlQ2hhbm5lbFJlcXVlc3QSPAoI", "YWdlbnRfaWQYASABKAsyKi5iZ3MucHJvdG9jb2wuYWNjb3VudC52MS5HYW1l", "QWNjb3VudEhhbmRsZRI+CgdvcHRpb25zGAIgASgLMi0uYmdzLnByb3RvY29s", "LmNoYW5uZWwudjIuQ3JlYXRlQ2hhbm5lbE9wdGlvbnMijgEKFkRpc3NvbHZl",
				"Q2hhbm5lbFJlcXVlc3QSPAoIYWdlbnRfaWQYASABKAsyKi5iZ3MucHJvdG9j", "b2wuYWNjb3VudC52MS5HYW1lQWNjb3VudEhhbmRsZRI2CgpjaGFubmVsX2lk", "GAIgASgLMiIuYmdzLnByb3RvY29sLmNoYW5uZWwudjIuQ2hhbm5lbElkIuoB", "ChFHZXRDaGFubmVsUmVxdWVzdBI8CghhZ2VudF9pZBgBIAEoCzIqLmJncy5w", "cm90b2NvbC5hY2NvdW50LnYxLkdhbWVBY2NvdW50SGFuZGxlEjYKCmNoYW5u", "ZWxfaWQYAiABKAsyIi5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5DaGFubmVs", "SWQSGAoQZmV0Y2hfYXR0cmlidXRlcxgFIAEoCBIVCg1mZXRjaF9tZW1iZXJz", "GAYgASgIEhkKEWZldGNoX2ludml0YXRpb25zGAcgASgIEhMKC2ZldGNoX3Jv", "bGVzGAggASgIIkcKEkdldENoYW5uZWxSZXNwb25zZRIxCgdjaGFubmVsGAEg", "ASgLMiAuYmdzLnByb3RvY29sLmNoYW5uZWwudjIuQ2hhbm5lbCK6AQocR2V0",
				"UHVibGljQ2hhbm5lbFR5cGVzUmVxdWVzdBI8CghhZ2VudF9pZBgBIAEoCzIq", "LmJncy5wcm90b2NvbC5hY2NvdW50LnYxLkdhbWVBY2NvdW50SGFuZGxlEkYK", "B29wdGlvbnMYAiABKAsyNS5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5HZXRQ", "dWJsaWNDaGFubmVsVHlwZXNPcHRpb25zEhQKDGNvbnRpbnVhdGlvbhgDIAEo", "BCJyCh1HZXRQdWJsaWNDaGFubmVsVHlwZXNSZXNwb25zZRI7CgdjaGFubmVs", "GAEgAygLMiouYmdzLnByb3RvY29sLmNoYW5uZWwudjIuUHVibGljQ2hhbm5l", "bFR5cGUSFAoMY29udGludWF0aW9uGAIgASgEIpABChJGaW5kQ2hhbm5lbFJl", "cXVlc3QSPAoIYWdlbnRfaWQYASABKAsyKi5iZ3MucHJvdG9jb2wuYWNjb3Vu", "dC52MS5HYW1lQWNjb3VudEhhbmRsZRI8CgdvcHRpb25zGAIgASgLMisuYmdz", "LnByb3RvY29sLmNoYW5uZWwudjIuRmluZENoYW5uZWxPcHRpb25zIogBChBT",
				"dWJzY3JpYmVSZXF1ZXN0EjwKCGFnZW50X2lkGAEgASgLMiouYmdzLnByb3Rv", "Y29sLmFjY291bnQudjEuR2FtZUFjY291bnRIYW5kbGUSNgoKY2hhbm5lbF9p", "ZBgCIAEoCzIiLmJncy5wcm90b2NvbC5jaGFubmVsLnYyLkNoYW5uZWxJZCJG", "ChFTdWJzY3JpYmVSZXNwb25zZRIxCgdjaGFubmVsGAEgASgLMiAuYmdzLnBy", "b3RvY29sLmNoYW5uZWwudjIuQ2hhbm5lbCKKAQoSVW5zdWJzY3JpYmVSZXF1", "ZXN0EjwKCGFnZW50X2lkGAEgASgLMiouYmdzLnByb3RvY29sLmFjY291bnQu", "djEuR2FtZUFjY291bnRIYW5kbGUSNgoKY2hhbm5lbF9pZBgCIAEoCzIiLmJn", "cy5wcm90b2NvbC5jaGFubmVsLnYyLkNoYW5uZWxJZCK6AQoTU2V0QXR0cmli", "dXRlUmVxdWVzdBI8CghhZ2VudF9pZBgBIAEoCzIqLmJncy5wcm90b2NvbC5h", "Y2NvdW50LnYxLkdhbWVBY2NvdW50SGFuZGxlEjYKCmNoYW5uZWxfaWQYAiAB",
				"KAsyIi5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5DaGFubmVsSWQSLQoJYXR0", "cmlidXRlGAMgAygLMhouYmdzLnByb3RvY29sLnYyLkF0dHJpYnV0ZSLMAQoW", "U2V0UHJpdmFjeUxldmVsUmVxdWVzdBI8CghhZ2VudF9pZBgBIAEoCzIqLmJn", "cy5wcm90b2NvbC5hY2NvdW50LnYxLkdhbWVBY2NvdW50SGFuZGxlEjYKCmNo", "YW5uZWxfaWQYAiABKAsyIi5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5DaGFu", "bmVsSWQSPAoNcHJpdmFjeV9sZXZlbBgDIAEoDjIlLmJncy5wcm90b2NvbC5j", "aGFubmVsLnYyLlByaXZhY3lMZXZlbCLIAQoSU2VuZE1lc3NhZ2VSZXF1ZXN0", "EjwKCGFnZW50X2lkGAEgASgLMiouYmdzLnByb3RvY29sLmFjY291bnQudjEu", "R2FtZUFjY291bnRIYW5kbGUSNgoKY2hhbm5lbF9pZBgCIAEoCzIiLmJncy5w", "cm90b2NvbC5jaGFubmVsLnYyLkNoYW5uZWxJZBI8CgdvcHRpb25zGAMgASgL",
				"MisuYmdzLnByb3RvY29sLmNoYW5uZWwudjIuU2VuZE1lc3NhZ2VPcHRpb25z", "Is4BChlTZXRUeXBpbmdJbmRpY2F0b3JSZXF1ZXN0EjwKCGFnZW50X2lkGAEg", "ASgLMiouYmdzLnByb3RvY29sLmFjY291bnQudjEuR2FtZUFjY291bnRIYW5k", "bGUSNgoKY2hhbm5lbF9pZBgCIAEoCzIiLmJncy5wcm90b2NvbC5jaGFubmVs", "LnYyLkNoYW5uZWxJZBI7CgZhY3Rpb24YAyABKA4yHS5iZ3MucHJvdG9jb2wu", "VHlwaW5nSW5kaWNhdG9yOgxUWVBJTkdfU1RBUlQiwQEKC0pvaW5SZXF1ZXN0", "EjwKCGFnZW50X2lkGAEgASgLMiouYmdzLnByb3RvY29sLmFjY291bnQudjEu", "R2FtZUFjY291bnRIYW5kbGUSNgoKY2hhbm5lbF9pZBgCIAEoCzIiLmJncy5w", "cm90b2NvbC5jaGFubmVsLnYyLkNoYW5uZWxJZBI8CgZtZW1iZXIYAyABKAsy", "LC5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5DcmVhdGVNZW1iZXJPcHRpb25z",
				"IoQBCgxMZWF2ZVJlcXVlc3QSPAoIYWdlbnRfaWQYASABKAsyKi5iZ3MucHJv", "dG9jb2wuYWNjb3VudC52MS5HYW1lQWNjb3VudEhhbmRsZRI2CgpjaGFubmVs", "X2lkGAIgASgLMiIuYmdzLnByb3RvY29sLmNoYW5uZWwudjIuQ2hhbm5lbElk", "IsIBCgtLaWNrUmVxdWVzdBI8CghhZ2VudF9pZBgBIAEoCzIqLmJncy5wcm90", "b2NvbC5hY2NvdW50LnYxLkdhbWVBY2NvdW50SGFuZGxlEjYKCmNoYW5uZWxf", "aWQYAiABKAsyIi5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5DaGFubmVsSWQS", "PQoJdGFyZ2V0X2lkGAMgASgLMiouYmdzLnByb3RvY29sLmFjY291bnQudjEu", "R2FtZUFjY291bnRIYW5kbGUi0wEKGVNldE1lbWJlckF0dHJpYnV0ZVJlcXVl", "c3QSPAoIYWdlbnRfaWQYASABKAsyKi5iZ3MucHJvdG9jb2wuYWNjb3VudC52", "MS5HYW1lQWNjb3VudEhhbmRsZRI2CgpjaGFubmVsX2lkGAIgASgLMiIuYmdz",
				"LnByb3RvY29sLmNoYW5uZWwudjIuQ2hhbm5lbElkEkAKCmFzc2lnbm1lbnQY", "AyABKAsyLC5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5BdHRyaWJ1dGVBc3Np", "Z25tZW50IsYBChFBc3NpZ25Sb2xlUmVxdWVzdBI8CghhZ2VudF9pZBgBIAEo", "CzIqLmJncy5wcm90b2NvbC5hY2NvdW50LnYxLkdhbWVBY2NvdW50SGFuZGxl", "EjYKCmNoYW5uZWxfaWQYAiABKAsyIi5iZ3MucHJvdG9jb2wuY2hhbm5lbC52", "Mi5DaGFubmVsSWQSOwoKYXNzaWdubWVudBgDIAEoCzInLmJncy5wcm90b2Nv", "bC5jaGFubmVsLnYyLlJvbGVBc3NpZ25tZW50IsgBChNVbmFzc2lnblJvbGVS", "ZXF1ZXN0EjwKCGFnZW50X2lkGAEgASgLMiouYmdzLnByb3RvY29sLmFjY291", "bnQudjEuR2FtZUFjY291bnRIYW5kbGUSNgoKY2hhbm5lbF9pZBgCIAEoCzIi", "LmJncy5wcm90b2NvbC5jaGFubmVsLnYyLkNoYW5uZWxJZBI7Cgphc3NpZ25t",
				"ZW50GAMgASgLMicuYmdzLnByb3RvY29sLmNoYW5uZWwudjIuUm9sZUFzc2ln", "bm1lbnQingEKFVNlbmRJbnZpdGF0aW9uUmVxdWVzdBI8CghhZ2VudF9pZBgB", "IAEoCzIqLmJncy5wcm90b2NvbC5hY2NvdW50LnYxLkdhbWVBY2NvdW50SGFu", "ZGxlEj8KB29wdGlvbnMYAiABKAsyLi5iZ3MucHJvdG9jb2wuY2hhbm5lbC52", "Mi5TZW5kSW52aXRhdGlvbk9wdGlvbnM6BoL5KwIIASKmAQoXQWNjZXB0SW52", "aXRhdGlvblJlcXVlc3QSPAoIYWdlbnRfaWQYASABKAsyKi5iZ3MucHJvdG9j", "b2wuYWNjb3VudC52MS5HYW1lQWNjb3VudEhhbmRsZRI2CgpjaGFubmVsX2lk", "GAIgASgLMiIuYmdzLnByb3RvY29sLmNoYW5uZWwudjIuQ2hhbm5lbElkEhUK", "DWludml0YXRpb25faWQYAyABKAYipwEKGERlY2xpbmVJbnZpdGF0aW9uUmVx", "dWVzdBI8CghhZ2VudF9pZBgBIAEoCzIqLmJncy5wcm90b2NvbC5hY2NvdW50",
				"LnYxLkdhbWVBY2NvdW50SGFuZGxlEjYKCmNoYW5uZWxfaWQYAiABKAsyIi5i", "Z3MucHJvdG9jb2wuY2hhbm5lbC52Mi5DaGFubmVsSWQSFQoNaW52aXRhdGlv", "bl9pZBgDIAEoBiKmAQoXUmV2b2tlSW52aXRhdGlvblJlcXVlc3QSPAoIYWdl", "bnRfaWQYASABKAsyKi5iZ3MucHJvdG9jb2wuYWNjb3VudC52MS5HYW1lQWNj", "b3VudEhhbmRsZRI2CgpjaGFubmVsX2lkGAIgASgLMiIuYmdzLnByb3RvY29s", "LmNoYW5uZWwudjIuQ2hhbm5lbElkEhUKDWludml0YXRpb25faWQYAyABKAYi", "ngEKFVNlbmRTdWdnZXN0aW9uUmVxdWVzdBI8CghhZ2VudF9pZBgBIAEoCzIq", "LmJncy5wcm90b2NvbC5hY2NvdW50LnYxLkdhbWVBY2NvdW50SGFuZGxlEj8K", "B29wdGlvbnMYAiABKAsyLi5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5TZW5k", "U3VnZ2VzdGlvbk9wdGlvbnM6BoL5KwIIASKhAQoYR2V0Sm9pblZvaWNlVG9r",
				"ZW5SZXF1ZXN0EjwKCGFnZW50X2lkGAEgASgLMiouYmdzLnByb3RvY29sLmFj", "Y291bnQudjEuR2FtZUFjY291bnRIYW5kbGUSNgoKY2hhbm5lbF9pZBgCIAEo", "CzIiLmJncy5wcm90b2NvbC5jaGFubmVsLnYyLkNoYW5uZWxJZBIPCgd2ZXJz", "aW9uGAMgASgNImUKGUdldEpvaW5Wb2ljZVRva2VuUmVzcG9uc2USEwoLY2hh", "bm5lbF91cmkYASABKAkSMwoLY3JlZGVudGlhbHMYAiABKAsyHi5iZ3MucHJv", "dG9jb2wuVm9pY2VDcmVkZW50aWFscyKDAgoXTWVtYmVyQWRkZWROb3RpZmlj", "YXRpb24SPAoIYWdlbnRfaWQYASABKAsyKi5iZ3MucHJvdG9jb2wuYWNjb3Vu", "dC52MS5HYW1lQWNjb3VudEhhbmRsZRJBCg1zdWJzY3JpYmVyX2lkGAIgASgL", "MiouYmdzLnByb3RvY29sLmFjY291bnQudjEuR2FtZUFjY291bnRIYW5kbGUS", "NgoKY2hhbm5lbF9pZBgDIAEoCzIiLmJncy5wcm90b2NvbC5jaGFubmVsLnYy",
				"LkNoYW5uZWxJZBIvCgZtZW1iZXIYBCABKAsyHy5iZ3MucHJvdG9jb2wuY2hh", "bm5lbC52Mi5NZW1iZXIiowIKGU1lbWJlclJlbW92ZWROb3RpZmljYXRpb24S", "PAoIYWdlbnRfaWQYASABKAsyKi5iZ3MucHJvdG9jb2wuYWNjb3VudC52MS5H", "YW1lQWNjb3VudEhhbmRsZRJBCg1zdWJzY3JpYmVyX2lkGAIgASgLMiouYmdz", "LnByb3RvY29sLmFjY291bnQudjEuR2FtZUFjY291bnRIYW5kbGUSNgoKY2hh", "bm5lbF9pZBgDIAEoCzIiLmJncy5wcm90b2NvbC5jaGFubmVsLnYyLkNoYW5u", "ZWxJZBI9CgltZW1iZXJfaWQYBCABKAsyKi5iZ3MucHJvdG9jb2wuYWNjb3Vu", "dC52MS5HYW1lQWNjb3VudEhhbmRsZRIOCgZyZWFzb24YBSABKA0inwIKIk1l", "bWJlckF0dHJpYnV0ZUNoYW5nZWROb3RpZmljYXRpb24SPAoIYWdlbnRfaWQY", "ASABKAsyKi5iZ3MucHJvdG9jb2wuYWNjb3VudC52MS5HYW1lQWNjb3VudEhh",
				"bmRsZRJBCg1zdWJzY3JpYmVyX2lkGAIgASgLMiouYmdzLnByb3RvY29sLmFj", "Y291bnQudjEuR2FtZUFjY291bnRIYW5kbGUSNgoKY2hhbm5lbF9pZBgDIAEo", "CzIiLmJncy5wcm90b2NvbC5jaGFubmVsLnYyLkNoYW5uZWxJZBJACgphc3Np", "Z25tZW50GAQgASgLMiwuYmdzLnByb3RvY29sLmNoYW5uZWwudjIuQXR0cmli", "dXRlQXNzaWdubWVudCKVAgodTWVtYmVyUm9sZUNoYW5nZWROb3RpZmljYXRp", "b24SPAoIYWdlbnRfaWQYASABKAsyKi5iZ3MucHJvdG9jb2wuYWNjb3VudC52", "MS5HYW1lQWNjb3VudEhhbmRsZRJBCg1zdWJzY3JpYmVyX2lkGAIgASgLMiou", "YmdzLnByb3RvY29sLmFjY291bnQudjEuR2FtZUFjY291bnRIYW5kbGUSNgoK", "Y2hhbm5lbF9pZBgDIAEoCzIiLmJncy5wcm90b2NvbC5jaGFubmVsLnYyLkNo", "YW5uZWxJZBI7Cgphc3NpZ25tZW50GAQgAygLMicuYmdzLnByb3RvY29sLmNo",
				"YW5uZWwudjIuUm9sZUFzc2lnbm1lbnQihgIKHEF0dHJpYnV0ZUNoYW5nZWRO", "b3RpZmljYXRpb24SPAoIYWdlbnRfaWQYASABKAsyKi5iZ3MucHJvdG9jb2wu", "YWNjb3VudC52MS5HYW1lQWNjb3VudEhhbmRsZRJBCg1zdWJzY3JpYmVyX2lk", "GAIgASgLMiouYmdzLnByb3RvY29sLmFjY291bnQudjEuR2FtZUFjY291bnRI", "YW5kbGUSNgoKY2hhbm5lbF9pZBgDIAEoCzIiLmJncy5wcm90b2NvbC5jaGFu", "bmVsLnYyLkNoYW5uZWxJZBItCglhdHRyaWJ1dGUYBCADKAsyGi5iZ3MucHJv", "dG9jb2wudjIuQXR0cmlidXRlIqwCCh9Qcml2YWN5TGV2ZWxDaGFuZ2VkTm90", "aWZpY2F0aW9uEjwKCGFnZW50X2lkGAEgASgLMiouYmdzLnByb3RvY29sLmFj", "Y291bnQudjEuR2FtZUFjY291bnRIYW5kbGUSQQoNc3Vic2NyaWJlcl9pZBgC", "IAEoCzIqLmJncy5wcm90b2NvbC5hY2NvdW50LnYxLkdhbWVBY2NvdW50SGFu",
				"ZGxlEjYKCmNoYW5uZWxfaWQYAyABKAsyIi5iZ3MucHJvdG9jb2wuY2hhbm5l", "bC52Mi5DaGFubmVsSWQSUAoNcHJpdmFjeV9sZXZlbBgEIAEoDjIlLmJncy5w", "cm90b2NvbC5jaGFubmVsLnYyLlByaXZhY3lMZXZlbDoSUFJJVkFDWV9MRVZF", "TF9PUEVOIowCChdTZW5kTWVzc2FnZU5vdGlmaWNhdGlvbhI8CghhZ2VudF9p", "ZBgBIAEoCzIqLmJncy5wcm90b2NvbC5hY2NvdW50LnYxLkdhbWVBY2NvdW50", "SGFuZGxlEkEKDXN1YnNjcmliZXJfaWQYAiABKAsyKi5iZ3MucHJvdG9jb2wu", "YWNjb3VudC52MS5HYW1lQWNjb3VudEhhbmRsZRI2CgpjaGFubmVsX2lkGAMg", "ASgLMiIuYmdzLnByb3RvY29sLmNoYW5uZWwudjIuQ2hhbm5lbElkEjgKB21l", "c3NhZ2UYBCABKAsyJy5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5DaGFubmVs", "TWVzc2FnZSLhAgobVHlwaW5nSW5kaWNhdG9yTm90aWZpY2F0aW9uEjwKCGFn",
				"ZW50X2lkGAEgASgLMiouYmdzLnByb3RvY29sLmFjY291bnQudjEuR2FtZUFj", "Y291bnRIYW5kbGUSQQoNc3Vic2NyaWJlcl9pZBgCIAEoCzIqLmJncy5wcm90", "b2NvbC5hY2NvdW50LnYxLkdhbWVBY2NvdW50SGFuZGxlEjYKCmNoYW5uZWxf", "aWQYAyABKAsyIi5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5DaGFubmVsSWQS", "PQoJYXV0aG9yX2lkGAQgASgLMiouYmdzLnByb3RvY29sLmFjY291bnQudjEu", "R2FtZUFjY291bnRIYW5kbGUSDQoFZXBvY2gYBSABKAQSOwoGYWN0aW9uGAYg", "ASgOMh0uYmdzLnByb3RvY29sLlR5cGluZ0luZGljYXRvcjoMVFlQSU5HX1NU", "QVJUIpYCChtJbnZpdGF0aW9uQWRkZWROb3RpZmljYXRpb24SPAoIYWdlbnRf", "aWQYASABKAsyKi5iZ3MucHJvdG9jb2wuYWNjb3VudC52MS5HYW1lQWNjb3Vu", "dEhhbmRsZRJBCg1zdWJzY3JpYmVyX2lkGAIgASgLMiouYmdzLnByb3RvY29s",
				"LmFjY291bnQudjEuR2FtZUFjY291bnRIYW5kbGUSNgoKY2hhbm5lbF9pZBgD", "IAEoCzIiLmJncy5wcm90b2NvbC5jaGFubmVsLnYyLkNoYW5uZWxJZBI+Cgpp", "bnZpdGF0aW9uGAQgASgLMiouYmdzLnByb3RvY29sLmNoYW5uZWwudjIuQ2hh", "bm5lbEludml0YXRpb24iygIKHUludml0YXRpb25SZW1vdmVkTm90aWZpY2F0", "aW9uEjwKCGFnZW50X2lkGAEgASgLMiouYmdzLnByb3RvY29sLmFjY291bnQu", "djEuR2FtZUFjY291bnRIYW5kbGUSQQoNc3Vic2NyaWJlcl9pZBgCIAEoCzIq", "LmJncy5wcm90b2NvbC5hY2NvdW50LnYxLkdhbWVBY2NvdW50SGFuZGxlEjYK", "CmNoYW5uZWxfaWQYAyABKAsyIi5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5D", "aGFubmVsSWQSFQoNaW52aXRhdGlvbl9pZBgEIAEoBhJZCgZyZWFzb24YBSAB", "KA4yJS5iZ3MucHJvdG9jb2wuSW52aXRhdGlvblJlbW92ZWRSZWFzb246IklO",
				"VklUQVRJT05fUkVNT1ZFRF9SRUFTT05fQUNDRVBURUQi1wEKG1N1Z2dlc3Rp", "b25BZGRlZE5vdGlmaWNhdGlvbhI8CghhZ2VudF9pZBgBIAEoCzIqLmJncy5w", "cm90b2NvbC5hY2NvdW50LnYxLkdhbWVBY2NvdW50SGFuZGxlEkEKDXN1YnNj", "cmliZXJfaWQYAiABKAsyKi5iZ3MucHJvdG9jb2wuYWNjb3VudC52MS5HYW1l", "QWNjb3VudEhhbmRsZRI3CgpzdWdnZXN0aW9uGAMgASgLMiMuYmdzLnByb3Rv", "Y29sLmNoYW5uZWwudjIuU3VnZ2VzdGlvbjKaEgoOQ2hhbm5lbFNlcnZpY2US", "XAoNQ3JlYXRlQ2hhbm5lbBItLmJncy5wcm90b2NvbC5jaGFubmVsLnYyLkNy", "ZWF0ZUNoYW5uZWxSZXF1ZXN0GhQuYmdzLnByb3RvY29sLk5vRGF0YSIGgvkr", "AggCEmAKD0Rpc3NvbHZlQ2hhbm5lbBIvLmJncy5wcm90b2NvbC5jaGFubmVs", "LnYyLkRpc3NvbHZlQ2hhbm5lbFJlcXVlc3QaFC5iZ3MucHJvdG9jb2wuTm9E",
				"YXRhIgaC+SsCCAMSbQoKR2V0Q2hhbm5lbBIqLmJncy5wcm90b2NvbC5jaGFu", "bmVsLnYyLkdldENoYW5uZWxSZXF1ZXN0GisuYmdzLnByb3RvY29sLmNoYW5u", "ZWwudjIuR2V0Q2hhbm5lbFJlc3BvbnNlIgaC+SsCCAQSjgEKFUdldFB1Ymxp", "Y0NoYW5uZWxUeXBlcxI1LmJncy5wcm90b2NvbC5jaGFubmVsLnYyLkdldFB1", "YmxpY0NoYW5uZWxUeXBlc1JlcXVlc3QaNi5iZ3MucHJvdG9jb2wuY2hhbm5l", "bC52Mi5HZXRQdWJsaWNDaGFubmVsVHlwZXNSZXNwb25zZSIGgvkrAggFElgK", "C0ZpbmRDaGFubmVsEisuYmdzLnByb3RvY29sLmNoYW5uZWwudjIuRmluZENo", "YW5uZWxSZXF1ZXN0GhQuYmdzLnByb3RvY29sLk5vRGF0YSIGgvkrAggGEmoK", "CVN1YnNjcmliZRIpLmJncy5wcm90b2NvbC5jaGFubmVsLnYyLlN1YnNjcmli", "ZVJlcXVlc3QaKi5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5TdWJzY3JpYmVS",
				"ZXNwb25zZSIGgvkrAggKElgKC1Vuc3Vic2NyaWJlEisuYmdzLnByb3RvY29s", "LmNoYW5uZWwudjIuVW5zdWJzY3JpYmVSZXF1ZXN0GhQuYmdzLnByb3RvY29s", "Lk5vRGF0YSIGgvkrAggLEloKDFNldEF0dHJpYnV0ZRIsLmJncy5wcm90b2Nv", "bC5jaGFubmVsLnYyLlNldEF0dHJpYnV0ZVJlcXVlc3QaFC5iZ3MucHJvdG9j", "b2wuTm9EYXRhIgaC+SsCCBUSYAoPU2V0UHJpdmFjeUxldmVsEi8uYmdzLnBy", "b3RvY29sLmNoYW5uZWwudjIuU2V0UHJpdmFjeUxldmVsUmVxdWVzdBoULmJn", "cy5wcm90b2NvbC5Ob0RhdGEiBoL5KwIIFhJYCgtTZW5kTWVzc2FnZRIrLmJn", "cy5wcm90b2NvbC5jaGFubmVsLnYyLlNlbmRNZXNzYWdlUmVxdWVzdBoULmJn", "cy5wcm90b2NvbC5Ob0RhdGEiBoL5KwIIFxJmChJTZXRUeXBpbmdJbmRpY2F0", "b3ISMi5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5TZXRUeXBpbmdJbmRpY2F0",
				"b3JSZXF1ZXN0GhQuYmdzLnByb3RvY29sLk5vRGF0YSIGgvkrAggYEkoKBEpv", "aW4SJC5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5Kb2luUmVxdWVzdBoULmJn", "cy5wcm90b2NvbC5Ob0RhdGEiBoL5KwIIHhJMCgVMZWF2ZRIlLmJncy5wcm90", "b2NvbC5jaGFubmVsLnYyLkxlYXZlUmVxdWVzdBoULmJncy5wcm90b2NvbC5O", "b0RhdGEiBoL5KwIIHxJKCgRLaWNrEiQuYmdzLnByb3RvY29sLmNoYW5uZWwu", "djIuS2lja1JlcXVlc3QaFC5iZ3MucHJvdG9jb2wuTm9EYXRhIgaC+SsCCCAS", "ZgoSU2V0TWVtYmVyQXR0cmlidXRlEjIuYmdzLnByb3RvY29sLmNoYW5uZWwu", "djIuU2V0TWVtYmVyQXR0cmlidXRlUmVxdWVzdBoULmJncy5wcm90b2NvbC5O", "b0RhdGEiBoL5KwIIKBJWCgpBc3NpZ25Sb2xlEiouYmdzLnByb3RvY29sLmNo", "YW5uZWwudjIuQXNzaWduUm9sZVJlcXVlc3QaFC5iZ3MucHJvdG9jb2wuTm9E",
				"YXRhIgaC+SsCCCkSWgoMVW5hc3NpZ25Sb2xlEiwuYmdzLnByb3RvY29sLmNo", "YW5uZWwudjIuVW5hc3NpZ25Sb2xlUmVxdWVzdBoULmJncy5wcm90b2NvbC5O", "b0RhdGEiBoL5KwIIKhJeCg5TZW5kSW52aXRhdGlvbhIuLmJncy5wcm90b2Nv", "bC5jaGFubmVsLnYyLlNlbmRJbnZpdGF0aW9uUmVxdWVzdBoULmJncy5wcm90", "b2NvbC5Ob0RhdGEiBoL5KwIIMhJiChBBY2NlcHRJbnZpdGF0aW9uEjAuYmdz", "LnByb3RvY29sLmNoYW5uZWwudjIuQWNjZXB0SW52aXRhdGlvblJlcXVlc3Qa", "FC5iZ3MucHJvdG9jb2wuTm9EYXRhIgaC+SsCCDMSZAoRRGVjbGluZUludml0", "YXRpb24SMS5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5EZWNsaW5lSW52aXRh", "dGlvblJlcXVlc3QaFC5iZ3MucHJvdG9jb2wuTm9EYXRhIgaC+SsCCDQSYgoQ", "UmV2b2tlSW52aXRhdGlvbhIwLmJncy5wcm90b2NvbC5jaGFubmVsLnYyLlJl",
				"dm9rZUludml0YXRpb25SZXF1ZXN0GhQuYmdzLnByb3RvY29sLk5vRGF0YSIG", "gvkrAgg1El4KDlNlbmRTdWdnZXN0aW9uEi4uYmdzLnByb3RvY29sLmNoYW5u", "ZWwudjIuU2VuZFN1Z2dlc3Rpb25SZXF1ZXN0GhQuYmdzLnByb3RvY29sLk5v", "RGF0YSIGgvkrAgg8EoIBChFHZXRKb2luVm9pY2VUb2tlbhIxLmJncy5wcm90", "b2NvbC5jaGFubmVsLnYyLkdldEpvaW5Wb2ljZVRva2VuUmVxdWVzdBoyLmJn", "cy5wcm90b2NvbC5jaGFubmVsLnYyLkdldEpvaW5Wb2ljZVRva2VuUmVzcG9u", "c2UiBoL5KwIIRhozgvkrKQonYm5ldC5wcm90b2NvbC5jaGFubmVsLnYyLkNo", "YW5uZWxTZXJ2aWNlivkrAhABMo0KCg9DaGFubmVsTGlzdGVuZXISZAoNT25N", "ZW1iZXJBZGRlZBIwLmJncy5wcm90b2NvbC5jaGFubmVsLnYyLk1lbWJlckFk", "ZGVkTm90aWZpY2F0aW9uGhkuYmdzLnByb3RvY29sLk5PX1JFU1BPTlNFIgaC",
				"+SsCCAMSaAoPT25NZW1iZXJSZW1vdmVkEjIuYmdzLnByb3RvY29sLmNoYW5u", "ZWwudjIuTWVtYmVyUmVtb3ZlZE5vdGlmaWNhdGlvbhoZLmJncy5wcm90b2Nv", "bC5OT19SRVNQT05TRSIGgvkrAggEEnoKGE9uTWVtYmVyQXR0cmlidXRlQ2hh", "bmdlZBI7LmJncy5wcm90b2NvbC5jaGFubmVsLnYyLk1lbWJlckF0dHJpYnV0", "ZUNoYW5nZWROb3RpZmljYXRpb24aGS5iZ3MucHJvdG9jb2wuTk9fUkVTUE9O", "U0UiBoL5KwIIBRJwChNPbk1lbWJlclJvbGVDaGFuZ2VkEjYuYmdzLnByb3Rv", "Y29sLmNoYW5uZWwudjIuTWVtYmVyUm9sZUNoYW5nZWROb3RpZmljYXRpb24a", "GS5iZ3MucHJvdG9jb2wuTk9fUkVTUE9OU0UiBoL5KwIIBhJkCg1PblNlbmRN", "ZXNzYWdlEjAuYmdzLnByb3RvY29sLmNoYW5uZWwudjIuU2VuZE1lc3NhZ2VO", "b3RpZmljYXRpb24aGS5iZ3MucHJvdG9jb2wuTk9fUkVTUE9OU0UiBoL5KwII",
				"ChJsChFPblR5cGluZ0luZGljYXRvchI0LmJncy5wcm90b2NvbC5jaGFubmVs", "LnYyLlR5cGluZ0luZGljYXRvck5vdGlmaWNhdGlvbhoZLmJncy5wcm90b2Nv", "bC5OT19SRVNQT05TRSIGgvkrAggLEm4KEk9uQXR0cmlidXRlQ2hhbmdlZBI1", "LmJncy5wcm90b2NvbC5jaGFubmVsLnYyLkF0dHJpYnV0ZUNoYW5nZWROb3Rp", "ZmljYXRpb24aGS5iZ3MucHJvdG9jb2wuTk9fUkVTUE9OU0UiBoL5KwIIEBJ0", "ChVPblByaXZhY3lMZXZlbENoYW5nZWQSOC5iZ3MucHJvdG9jb2wuY2hhbm5l", "bC52Mi5Qcml2YWN5TGV2ZWxDaGFuZ2VkTm90aWZpY2F0aW9uGhkuYmdzLnBy", "b3RvY29sLk5PX1JFU1BPTlNFIgaC+SsCCBESbAoRT25JbnZpdGF0aW9uQWRk", "ZWQSNC5iZ3MucHJvdG9jb2wuY2hhbm5lbC52Mi5JbnZpdGF0aW9uQWRkZWRO", "b3RpZmljYXRpb24aGS5iZ3MucHJvdG9jb2wuTk9fUkVTUE9OU0UiBoL5KwII",
				"EhJwChNPbkludml0YXRpb25SZW1vdmVkEjYuYmdzLnByb3RvY29sLmNoYW5u", "ZWwudjIuSW52aXRhdGlvblJlbW92ZWROb3RpZmljYXRpb24aGS5iZ3MucHJv", "dG9jb2wuTk9fUkVTUE9OU0UiBoL5KwIIExJsChFPblN1Z2dlc3Rpb25BZGRl", "ZBI0LmJncy5wcm90b2NvbC5jaGFubmVsLnYyLlN1Z2dlc3Rpb25BZGRlZE5v", "dGlmaWNhdGlvbhoZLmJncy5wcm90b2NvbC5OT19SRVNQT05TRSIGgvkrAggU", "GjSC+SsqCihibmV0LnByb3RvY29sLmNoYW5uZWwudjIuQ2hhbm5lbExpc3Rl", "bmVyivkrAggBQgOAAQA="
			}));
			ChannelServiceReflection.descriptor = FileDescriptor.FromGeneratedCode(array, new FileDescriptor[]
			{
				ChannelTypesReflection.Descriptor,
				RpcTypesReflection.Descriptor,
				MessageTypesReflection.Descriptor,
				InvitationTypesReflection.Descriptor,
				VoiceTypesReflection.Descriptor
			}, new GeneratedClrTypeInfo(null, null, new GeneratedClrTypeInfo[]
			{
				new GeneratedClrTypeInfo(typeof(CreateChannelRequest), CreateChannelRequest.Parser, new string[] { "AgentId", "Options" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DissolveChannelRequest), DissolveChannelRequest.Parser, new string[] { "AgentId", "ChannelId" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(GetChannelRequest), GetChannelRequest.Parser, new string[] { "AgentId", "ChannelId", "FetchAttributes", "FetchMembers", "FetchInvitations", "FetchRoles" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(GetChannelResponse), GetChannelResponse.Parser, new string[] { "Channel" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(GetPublicChannelTypesRequest), GetPublicChannelTypesRequest.Parser, new string[] { "AgentId", "Options", "Continuation" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(GetPublicChannelTypesResponse), GetPublicChannelTypesResponse.Parser, new string[] { "Channel", "Continuation" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(FindChannelRequest), FindChannelRequest.Parser, new string[] { "AgentId", "Options" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(SubscribeRequest), SubscribeRequest.Parser, new string[] { "AgentId", "ChannelId" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(SubscribeResponse), SubscribeResponse.Parser, new string[] { "Channel" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(UnsubscribeRequest), UnsubscribeRequest.Parser, new string[] { "AgentId", "ChannelId" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(SetAttributeRequest), SetAttributeRequest.Parser, new string[] { "AgentId", "ChannelId", "Attribute" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(SetPrivacyLevelRequest), SetPrivacyLevelRequest.Parser, new string[] { "AgentId", "ChannelId", "PrivacyLevel" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(SendMessageRequest), SendMessageRequest.Parser, new string[] { "AgentId", "ChannelId", "Options" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(SetTypingIndicatorRequest), SetTypingIndicatorRequest.Parser, new string[] { "AgentId", "ChannelId", "Action" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(JoinRequest), JoinRequest.Parser, new string[] { "AgentId", "ChannelId", "Member" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(LeaveRequest), LeaveRequest.Parser, new string[] { "AgentId", "ChannelId" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(KickRequest), KickRequest.Parser, new string[] { "AgentId", "ChannelId", "TargetId" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(SetMemberAttributeRequest), SetMemberAttributeRequest.Parser, new string[] { "AgentId", "ChannelId", "Assignment" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AssignRoleRequest), AssignRoleRequest.Parser, new string[] { "AgentId", "ChannelId", "Assignment" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(UnassignRoleRequest), UnassignRoleRequest.Parser, new string[] { "AgentId", "ChannelId", "Assignment" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(SendInvitationRequest), SendInvitationRequest.Parser, new string[] { "AgentId", "Options" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AcceptInvitationRequest), AcceptInvitationRequest.Parser, new string[] { "AgentId", "ChannelId", "InvitationId" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DeclineInvitationRequest), DeclineInvitationRequest.Parser, new string[] { "AgentId", "ChannelId", "InvitationId" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(RevokeInvitationRequest), RevokeInvitationRequest.Parser, new string[] { "AgentId", "ChannelId", "InvitationId" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(SendSuggestionRequest), SendSuggestionRequest.Parser, new string[] { "AgentId", "Options" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(GetJoinVoiceTokenRequest), GetJoinVoiceTokenRequest.Parser, new string[] { "AgentId", "ChannelId", "Version" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(GetJoinVoiceTokenResponse), GetJoinVoiceTokenResponse.Parser, new string[] { "ChannelUri", "Credentials" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(MemberAddedNotification), MemberAddedNotification.Parser, new string[] { "AgentId", "SubscriberId", "ChannelId", "Member" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(MemberRemovedNotification), MemberRemovedNotification.Parser, new string[] { "AgentId", "SubscriberId", "ChannelId", "MemberId", "Reason" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(MemberAttributeChangedNotification), MemberAttributeChangedNotification.Parser, new string[] { "AgentId", "SubscriberId", "ChannelId", "Assignment" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(MemberRoleChangedNotification), MemberRoleChangedNotification.Parser, new string[] { "AgentId", "SubscriberId", "ChannelId", "Assignment" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AttributeChangedNotification), AttributeChangedNotification.Parser, new string[] { "AgentId", "SubscriberId", "ChannelId", "Attribute" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(PrivacyLevelChangedNotification), PrivacyLevelChangedNotification.Parser, new string[] { "AgentId", "SubscriberId", "ChannelId", "PrivacyLevel" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(SendMessageNotification), SendMessageNotification.Parser, new string[] { "AgentId", "SubscriberId", "ChannelId", "Message" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(TypingIndicatorNotification), TypingIndicatorNotification.Parser, new string[] { "AgentId", "SubscriberId", "ChannelId", "AuthorId", "Epoch", "Action" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(InvitationAddedNotification), InvitationAddedNotification.Parser, new string[] { "AgentId", "SubscriberId", "ChannelId", "Invitation" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(InvitationRemovedNotification), InvitationRemovedNotification.Parser, new string[] { "AgentId", "SubscriberId", "ChannelId", "InvitationId", "Reason" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(SuggestionAddedNotification), SuggestionAddedNotification.Parser, new string[] { "AgentId", "SubscriberId", "Suggestion" }, null, null, null, null)
			}));
		}

		// Token: 0x04004432 RID: 17458
		private static FileDescriptor descriptor;
	}
}
