using System;
using Fenris.Achievements;
using Fenris.Hero;
using Fenris.Items;
using Fenris.Online;
using Google.Protobuf.Reflection;

namespace Fenris.GameMessage
{
	// Token: 0x020001B9 RID: 441
	public static class GameMessageReflection
	{
		// Token: 0x17000ECB RID: 3787
		// (get) Token: 0x06002E60 RID: 11872 RVA: 0x000B520C File Offset: 0x000B340C
		public static FileDescriptor Descriptor
		{
			get
			{
				return GameMessageReflection.descriptor;
			}
		}

		// Token: 0x06002E61 RID: 11873 RVA: 0x000B5224 File Offset: 0x000B3424
		static GameMessageReflection()
		{
			byte[] array = Convert.FromBase64String(string.Concat(new string[]
			{
				"ChFHYW1lTWVzc2FnZS5wcm90bxISRmVucmlzLkdhbWVNZXNzYWdlGgpIZXJv", "LnByb3RvGgtJdGVtcy5wcm90bxoSQWNoaWV2ZW1lbnRzLnByb3RvGgxPbmxp", "bmUucHJvdG8iWAoPVHV0b3JpYWxNZXNzYWdlEhcKDHR1dG9yaWFsX3NubxgB", "IAEoDToBMBIWCg51aV9hbmNob3JfbmFtZRgCIAEoCRIUCghhY3Rvcl9pZBgD", "IAEoEToCLTEiNwoXSW5pdGlhbExvZ2luRGF0YVJlcXVlc3QSHAoRY291bnRy", "eV9pZF9mb3VyY2MYASABKA06ATAiWQoeSW5pdGlhbExvZ2luRGF0YVF1ZXVl", "ZFJlc3BvbnNlEhUKCnNlcnZpY2VfaWQYASABKA06ATASIAoVdGltZW91dF90", "aWNrX2ludGVydmFsGAIgASgNOgEwIhgKFkNhbmNlbExvZ2luRGF0YVJlcXVl", "c3QiswEKEVN0YXJ0R2FtZVRyYW5zZmVyEg8KB2dhbWVfaWQYASABKAcSFAoM", "Z2FtZV9hZGRyZXNzGAIgASgJEhEKCWdhbWVfcG9ydBgDIAEoDRI0CgZwbGF5",
				"ZXIYBCADKAsyJC5GZW5yaXMuT25saW5lLkNvbm5lY3Rpb25JbmZvLlBsYXll", "chIYChBnYW1lX3N1YnpvbmVfc25vGAUgASgPEhQKDHRyaWdnZXJfZmFkZRgG", "IAEoCCJSCgxNYWlsQ29udGVudHMSHgoPYXBwZW5kX21lc3NhZ2VzGAEgASgI", "OgVmYWxzZRIiCgVtYWlscxgCIAEoCzITLkZlbnJpcy5JdGVtcy5NYWlscyL3", "AQoNUGxheWVyQ29tbWFuZBIZCg5tX2NvbW1hbmRGcmFtZRgBIAEoDToBMBIQ", "CgVtX3lhdxgCIAEoDToBMBIXCgxtX3Rocm90dGxlX3gYAyABKBE6ATASFwoM", "bV90aHJvdHRsZV95GAQgASgROgEwEhcKDG1faW5wdXRGbGFncxgFIAEoDToB", "MBIaCg9tX3RlbGVwb3J0SW5kZXgYBiABKA06ATASGgoPbV9kZXN0aW5hdGlv", "bl94GAcgASgROgEwEhoKD21fZGVzdGluYXRpb25feRgIIAEoEToBMBIaCg9t", "X2Rlc3RpbmF0aW9uX3oYCSABKBE6ATAiqgYKG1BoeXNpY3NNb3ZlbWVudFN0",
				"YXRlTWVzc2FnZRIQCgVtX2FubhgBIAEoBzoBMBIZCgptX2lzX2RlbHRhGAIg", "ASgIOgVmYWxzZRIgChFtX2lzX3RhcmdldF9zdGF0ZRgDIAEoCDoFZmFsc2US", "EgoHbV9mbGFncxgEIAEoDToBMBIaCg9tX2NvbW1hbmRfZnJhbWUYBSABKA06", "ATASGwoQbV90ZWxlcG9ydF9pbmRleBgGIAEoDToBMBIaChJtX3dvcmxkX2xv", "Y2F0aW9uX3gYByABKBESGgoSbV93b3JsZF9sb2NhdGlvbl95GAggASgREhoK", "Em1fd29ybGRfbG9jYXRpb25fehgJIAEoERIUCgxtX3ZlbG9jaXR5X3gYCiAB", "KBESFAoMbV92ZWxvY2l0eV95GAsgASgREhQKDG1fdmVsb2NpdHlfehgMIAEo", "ERIZChFtX3ZlbF9mcm9tX2dyYXZfeBgNIAEoERIZChFtX3ZlbF9mcm9tX2dy", "YXZfeRgOIAEoERIZChFtX3ZlbF9mcm9tX2dyYXZfehgPIAEoERIYChBtX2Fu", "aW1faW1wdWxzZV94GBAgASgREhgKEG1fYW5pbV9pbXB1bHNlX3kYESABKBES",
				"GAoQbV9hbmltX2ltcHVsc2VfehgSIAEoERISCgptX2ZvcmNlc194GBMgASgR", "EhIKCm1fZm9yY2VzX3kYFCABKBESEgoKbV9mb3JjZXNfehgVIAEoERIQCgVt", "X3lhdxgWIAEoEToBMBIYCg1tX2Rlc2lyZWRfeWF3GBcgASgROgEwEhYKC21f", "eWF3X3NwZWVkGBggASgROgEwEhIKB21fc3BlZWQYGSABKBE6ATASKQoebV9h", "bmltYXRpb25fc2NhbGluZ190aW1lX3NjYWxlGBogASgROgEwEjMKJG1fY3Vy", "cmVudF9tb3Rpb25faXNfYW5pbWF0aW9uX2RyaXZlbhgbIAEoCDoFZmFsc2US", "JQodbV9zbm9fcG93ZXJfYW5pbV9rZXlfb3ZlcnJpZGUYHSABKA8SHwoUbV9w", "cmV2X2NvbW1hbmRfZnJhbWUYHiABKA06ATAiOAoSUG9seWdvblJlZ2lvblBv", "aW50EhAKBXBvc194GAEgASgCOgEwEhAKBXBvc195GAIgASgCOgEwInkKDVBv", "bHlnb25SZWdpb24SFwoMY2VudGVyX3Bvc194GAEgASgCOgEwEhcKDGNlbnRl",
				"cl9wb3NfeRgCIAEoAjoBMBI2CgZwb2ludHMYAyADKAsyJi5GZW5yaXMuR2Ft", "ZU1lc3NhZ2UuUG9seWdvblJlZ2lvblBvaW50Ir4FChhNaW5pbWFwTWFya2Vy", "SW5mb01lc3NhZ2USFwoPZ2FtZV9hY2NvdW50X2lkGAEgASgNEg8KB2lkX3Bp", "bmcYAiABKA0SEAoFcG9zX3gYBCABKAI6ATASEAoFcG9zX3kYBSABKAI6ATAS", "EAoFcG9zX3oYBiABKAI6ATASEQoJaWRfc3dvcmxkGBwgASgHEhEKCXNub193", "b3JsZBgHIAEoDxIWCg5zbm9fbGV2ZWxfYXJlYRgdIAEoDxIUCgxpbWFnZV9o", "YW5kbGUYCCABKA0SFwoPc25vX3N0cmluZ19saXN0GAkgASgPEhsKE3N0cmlu", "Z19sYWJlbF9oYW5kbGUYCiABKA0SDgoGYWN0aXZlGAsgASgIEhsKE3Jlc3Bl", "Y3RzX2ZvZ19vZl93YXIYDCABKAgSHgoWcmVzcGVjdHNfZXhwbG9yZWRfYXJl", "YRgNIAEoCBIPCgdpc19waW5nGA4gASgIEhgKEHVzZXNfYXJlYV9yYWRpdXMY",
				"DyABKAgSFwoPZnJvbV9iYWtlZF9kYXRhGBAgASgIEhUKDWlzX2RlYnVnX3Bp", "bmcYESABKAgSHAoUbWF4X2Rpc3BsYXlfcmFuZ2Vfc3EYEiABKAISGQoRZGlz", "Y292ZXJfcmFuZ2Vfc3EYEyABKAISGQoRcXVlc3RfYXJlYV9yYWRpdXMYFCAB", "KAISGAoQc25vX3F1ZXN0X3NvdXJjZRgWIAEoDxIXCg9xdWVzdF9waGFzZV91", "aWQYFyABKA0SGgoScXVlc3RfY2FsbGJhY2tfdWlkGBggASgNEhoKEnNlcnZl", "cl9tYXJrZXJfdHlwZRgZIAEoBRIWCg5zbm9fZGVzdF93b3JsZBgaIAEoDxI5", "Cg5wb2x5Z29uX3JlZ2lvbhgbIAEoCzIhLkZlbnJpcy5HYW1lTWVzc2FnZS5Q", "b2x5Z29uUmVnaW9uIpEBChZab25lUHJvZ3Jlc3NSZXdhcmREYXRhEhMKC3Jl", "d2FyZF90eXBlGAEgASgFEhcKD3Nub19pdGVtX3Jld2FyZBgCIAEoDxIaChJz", "bm9fdHJhY2tlZF9yZXdhcmQYAyABKA8SEQoJZ29sZF90aWVyGAQgASgFEhoK",
				"EnN0YXRpY19nb2xkX2Ftb3VudBgFIAEoBSKHAQodWm9uZVByb2dyZXNzUmV3", "YXJkUGVyVGllckRhdGESOwoHcmV3YXJkcxgBIAMoCzIqLkZlbnJpcy5HYW1l", "TWVzc2FnZS5ab25lUHJvZ3Jlc3NSZXdhcmREYXRhEhgKEHN0YXRpY194cF9y", "ZXdhcmQYAiABKAUSDwoHeHBfdGllchgDIAEoBSL5AQodWm9uZVByb2dyZXNz", "UGVyWm9uZUdsb2JhbERhdGESEQoJc25vX2NhbXBzGAEgAygPEhQKDHNub19k", "dW5nZW9ucxgCIAMoDxIWCg5zbm9fZm9nX29mX3dhchgDIAMoDxIXCg9zbm9f", "c2lkZV9xdWVzdHMYBCADKA8SFQoNc25vX3dheXBvaW50cxgFIAMoDxIaChJn", "YmlkX2hpZGRlbl9jYWNoZXMYBiADKA8SSwoQcmV3YXJkc19wZXJfdGllchgH", "IAMoCzIxLkZlbnJpcy5HYW1lTWVzc2FnZS5ab25lUHJvZ3Jlc3NSZXdhcmRQ", "ZXJUaWVyRGF0YSJLChpab25lUHJvZ3Jlc3NXb3JsZFRvRFBPRGF0YRIRCglz",
				"bm9fd29ybGQYASABKA8SGgoSc25vX2R1bmdlb25fcXVlc3RzGAIgAygPIsAC", "Ch1ab25lUHJvZ3Jlc3NHbG9iYWxEYXRhTWVzc2FnZRJICg1wZXJfem9uZV9k", "YXRhGAEgAygLMjEuRmVucmlzLkdhbWVNZXNzYWdlLlpvbmVQcm9ncmVzc1Bl", "clpvbmVHbG9iYWxEYXRhEiAKGHJlbm93bl9wZXJfcHJvZ3Jlc3NfdHlwZRgC", "IAMoBRIjChtyZW5vd25fcGVyX3Jld2FyZF90aHJlc2hvbGQYAyADKAUSHQoV", "cmV3YXJkX3N0cmluZ19oYW5kbGVzGAQgAygNEiUKHXRyYWNrZWRfcmV3YXJk", "X3N0cmluZ19oYW5kbGVzGAUgAygNEkgKEHdvcmxkX3RvX2Rwb19tYXAYBiAD", "KAsyLi5GZW5yaXMuR2FtZU1lc3NhZ2UuWm9uZVByb2dyZXNzV29ybGRUb0RQ", "T0RhdGEiXgoPRGVidWdXb3JsZFBsYWNlEhUKCXdvcmxkX3NubxgBIAEoDzoC", "LTESEAoFcG9zX3gYAiABKAI6ATASEAoFcG9zX3kYAyABKAI6ATASEAoFcG9z",
				"X3oYBCABKAI6ATAiiAEKC0RlYnVnVGFyZ2V0EhAKCGFjZF9uYW1lGAEgASgJ", "EjgKC3dvcmxkX3BsYWNlGAIgASgLMiMuRmVucmlzLkdhbWVNZXNzYWdlLkRl", "YnVnV29ybGRQbGFjZRIQCghwYXRoYWJsZRgDIAEoCBIbChN0aW1lX3NpbmNl", "X3BhdGhhYmxlGAQgASgCIm4KF1Byb2dyZXNzRGlhYmxvRXZlbnRMb290EiUK", "BGl0ZW0YASABKAsyFy5GZW5yaXMuSXRlbXMuR2VuZXJhdG9yEhAKCGVxdWlw", "cGVkGAIgASgIEhoKEnRyZWFzdXJlX2NsYXNzX3NubxgDIAEoDyJNChtQcm9n", "cmVzc0RpYWJsb0V2ZW50Q3VycmVuY3kSFQoNY3VycmVuY3lfdHlwZRgBIAEo", "BRIXCg9jdXJyZW5jeV9hbW91bnQYAiABKAQi5gUKE1Byb2dyZXNzRGlhYmxv", "RXZlbnQSEQoJYWN0b3Jfc25vGAIgASgPEhYKDmxldmVsX2FyZWFfc25vGAMg", "ASgPEiEKGW1vbnN0ZXJfY29tYmF0X2l0ZW1fcG93ZXIYBCABKAUSIAoYcGxh",
				"eWVyX2NvbWJhdF9pdGVtX3Bvd2VyGAUgASgFEjkKBGxvb3QYBiADKAsyKy5G", "ZW5yaXMuR2FtZU1lc3NhZ2UuUHJvZ3Jlc3NEaWFibG9FdmVudExvb3QSGQoR", "ZXhwZXJpZW5jZV9nYWluZWQYByABKA0SFgoObW9uc3Rlcl9yYXJpdHkYCCAB", "KAUSFAoMcGxheWVyX2xldmVsGAkgASgFEhUKDW1vbnN0ZXJfbGV2ZWwYCiAB", "KAUSHQoVcGxheWVyX2xldmVsX3Byb2dyZXNzGAsgASgCEhsKE2l0ZW1fcXVh", "bGl0eV9jb3VudHMYDCADKAUSHgoWcGxheWVyX2xvb3RfaXRlbV9wb3dlchgN", "IAEoBRInCh9wbGF5ZXJfYXR0YWNrX3JhdGluZ19mcm9tX2l0ZW1zGA4gASgF", "EigKIHBsYXllcl9kZWZlbnNlX3JhdGluZ19mcm9tX2l0ZW1zGA8gASgFEikK", "IXBsYXllcl9hdHRhY2tfZGVmZW5zZV9sZXZlbF9ib251cxgQIAEoBRIiChpw", "bGF5ZXJfYXR0YWNrX3JhdGluZ190b3RhbBgRIAEoBRIjChtwbGF5ZXJfZGVm",
				"ZW5zZV9yYXRpbmdfdG90YWwYEiABKAUSGAoQZXhwZXJpZW5jZV90b3RhbBgT", "IAEoBBImCh5nb2xkX2Zyb21fdmVuZG9yZWRfaXRlbXNfdG90YWwYFCABKAQS", "HAoUZ29sZF9mcm9tX2xvb3RfdG90YWwYFSABKAQSQQoIY3VycmVuY3kYFiAD", "KAsyLy5GZW5yaXMuR2FtZU1lc3NhZ2UuUHJvZ3Jlc3NEaWFibG9FdmVudEN1", "cnJlbmN5ImwKFFByb2dyZXNzRGlhYmxvVXBkYXRlEjcKBmV2ZW50cxgBIAMo", "CzInLkZlbnJpcy5HYW1lTWVzc2FnZS5Qcm9ncmVzc0RpYWJsb0V2ZW50EhsK", "E2NvbXBsZXRlZF9ydW5fY291bnQYAiABKAUimAEKFVByb2dyZXNzRGlhYmxv", "UmVxdWVzdBJZChJlbmRfY29uZGl0aW9uX3R5cGUYASABKA4yMi5GZW5yaXMu", "R2FtZU1lc3NhZ2UuUHJvZ3Jlc3NEaWFibG9FbmRDb25kaXRpb25UeXBlOglS", "VU5fQ09VTlQSEAoIcnVuX2dvYWwYAiABKAUSEgoKbGV2ZWxfZ29hbBgDIAEo",
				"BSKAAQoPQUlEZWJ1Z1ZhcmlhYmxlEgwKBG5hbWUYASABKAkSEQoJbmFtZV9o", "YXNoGAIgASgNEg0KBXZhbHVlGAMgASgCEh4KFnRpY2tzX3VudGlsX2V4cGly", "YXRpb24YBCABKA0SHQoVc291cmNlX2FpYmVoYXZpb3Jfc25vGAUgASgPInYK", "IkFJU3RhdGVEZWJ1Z1NuYXBzaG90RW50cnlDb25kaXRpb24SDAoEbmFtZRgB", "IAEoCRIRCglldmFsdWF0ZWQYAiABKAgSDgoGZmFpbGVkGAMgASgIEg4KBnJl", "c3VsdBgEIAEoBRIPCgdlbmFibGVkGAUgASgIIpcFChlBSVN0YXRlRGVidWdT", "bmFwc2hvdEVudHJ5EgwKBG5hbWUYASABKAkSEQoJcG93ZXJfc25vGAIgASgP", "EhkKEXBvd2VyX3RhcmdldF9uYW1lGAMgASgJEhsKE2Fpc3RhdGVfc3dpdGNo", "X25hbWUYBCABKAkSIAoYYWlzdGF0ZV9zd2l0Y2hfbmFtZV9oYXNoGAUgASgN", "ElAKEHN0YXJ0X2NvbmRpdGlvbnMYBiADKAsyNi5GZW5yaXMuR2FtZU1lc3Nh",
				"Z2UuQUlTdGF0ZURlYnVnU25hcHNob3RFbnRyeUNvbmRpdGlvbhJUChRpbnRl", "cnJ1cHRfY29uZGl0aW9ucxgHIAMoCzI2LkZlbnJpcy5HYW1lTWVzc2FnZS5B", "SVN0YXRlRGVidWdTbmFwc2hvdEVudHJ5Q29uZGl0aW9uEiAKGGNvb2xkb3du", "X3RpY2tzX3JlbWFpbmluZxgIIAEoDRIaChJpc19jdXJyZW50X3ByaW1hcnkY", "CSABKAgSEQoJZXZhbHVhdGVkGAogASgIEg4KBmZhaWxlZBgLIAEoCBIQCghz", "ZWxlY3RlZBgMIAEoCBIkChxwb3dlcl9mYWlsdXJlX3JlYXNvbnNfc3RyaW5n", "GA0gASgJEhQKDGNvb2xkb3duX2tleRgOIAEoBBIPCgdlbmFibGVkGA8gASgI", "EhgKEGV2YWx1YXRpb25fb3JkZXIYECABKA0SDgoGd2VpZ2h0GBEgASgNEhIK", "CnRhcmdldF9hbm4YEiABKA0SPwoSdGFyZ2V0X3dvcmxkX3BsYWNlGBMgASgL", "MiMuRmVucmlzLkdhbWVNZXNzYWdlLkRlYnVnV29ybGRQbGFjZRIYChB2YXJp",
				"YW50X21pc21hdGNoGBQgASgIIp8BCiBBSVN0YXRlRGVidWdTbmFwc2hvdEN1", "cnJlbnRQb3dlchIVCglwb3dlcl9zbm8YASABKA86Ai0xEhoKEm9yaWdpbmFs", "X3Bvd2VyX3NubxgCIAEoDxIvCgZ0YXJnZXQYAyABKAsyHy5GZW5yaXMuR2Ft", "ZU1lc3NhZ2UuRGVidWdUYXJnZXQSFwoPdGlja3NfZXhlY3V0aW5nGAQgASgN", "ImMKG0FJU3RhdGVEZWJ1Z1NuYXBzaG90UmV0cmVhdBIWCg5yZXRyZWF0X3Jh", "ZGl1cxgBIAEoAhIYChB0ZXRoZXJfdHlwZV9uYW1lGAIgASgJEhIKCnJldHJl", "YXRpbmcYAyABKAgilgEKF0FJVmFyaWFibGVEZWJ1Z1NuYXBzaG90EjwKD2xv", "Y2FsX3ZhcmlhYmxlcxgBIAMoCzIjLkZlbnJpcy5HYW1lTWVzc2FnZS5BSURl", "YnVnVmFyaWFibGUSPQoQcmVtb3RlX3ZhcmlhYmxlcxgCIAMoCzIjLkZlbnJp", "cy5HYW1lTWVzc2FnZS5BSURlYnVnVmFyaWFibGUijQcKFEFJU3RhdGVEZWJ1",
				"Z1NuYXBzaG90Eg4KA2FubhgBIAEoBzoBMBIYCg1jb21tYW5kX2ZyYW1lGAIg", "ASgNOgEwEjgKC3dvcmxkX3BsYWNlGAMgASgLMiMuRmVucmlzLkdhbWVNZXNz", "YWdlLkRlYnVnV29ybGRQbGFjZRILCgN5YXcYBCABKAISSwoNY3VycmVudF9w", "b3dlchgFIAEoCzI0LkZlbnJpcy5HYW1lTWVzc2FnZS5BSVN0YXRlRGVidWdT", "bmFwc2hvdEN1cnJlbnRQb3dlchIcChRwcmltYXJ5X2Fpc3RhdGVfbmFtZRgG", "IAEoCRIgChh0aWNrc19pbl9wcmltYXJ5X2Fpc3RhdGUYByABKA0SIgoacXVl", "dWVkX2Fpc3RhdGVfc3dpdGNoX25hbWUYCCABKAkSPgoHZW50cmllcxgJIAMo", "CzItLkZlbnJpcy5HYW1lTWVzc2FnZS5BSVN0YXRlRGVidWdTbmFwc2hvdEVu", "dHJ5EhwKFG1lcmdlZF9haXN0YXRlX25hbWVzGAogAygJEjgKD2hvc3RpbGVf", "dGFyZ2V0cxgLIAMoCzIfLkZlbnJpcy5HYW1lTWVzc2FnZS5EZWJ1Z1Rhcmdl",
				"dBI5ChBmcmllbmRseV90YXJnZXRzGAwgAygLMh8uRmVucmlzLkdhbWVNZXNz", "YWdlLkRlYnVnVGFyZ2V0EjcKDmFpcHJvcF90YXJnZXRzGA0gAygLMh8uRmVu", "cmlzLkdhbWVNZXNzYWdlLkRlYnVnVGFyZ2V0Eh8KF2N1cnJlbnRfYWliZWhh", "dmlvcl9uYW1lGA4gASgJEkYKEXZhcmlhYmxlX3NuYXBzaG90GA8gASgLMisu", "RmVucmlzLkdhbWVNZXNzYWdlLkFJVmFyaWFibGVEZWJ1Z1NuYXBzaG90Ei0K", "JXF1ZXVlZF9haXN0YXRlX3N3aXRjaF90aWNrc19yZW1haW5pbmcYECABKA0S", "KQohcXVldWVkX2Fpc3RhdGVfc3dpdGNoX2VudHJ5X2luZGV4GBEgASgNEjcK", "DmNhY2hlZF90YXJnZXRzGBIgAygLMh8uRmVucmlzLkdhbWVNZXNzYWdlLkRl", "YnVnVGFyZ2V0EhsKE2ZvcmNlZF9jb29sZG93bl9rZXkYEyABKAQSFwoPZm9y", "Y2VkX2Nvb2xkb3duGBQgASgCEhUKDWNob3Nlbl93ZWlnaHQYFSABKA0ikAEK",
				"HEFJU3RhdGVEZWJ1Z1JlYWxUaW1lU25hcHNob3QSDgoDYW5uGAEgASgHOgEw", "EhgKDWNvbW1hbmRfZnJhbWUYAiABKA06ATASRgoRdmFyaWFibGVfc25hcHNo", "b3QYAyABKAsyKy5GZW5yaXMuR2FtZU1lc3NhZ2UuQUlWYXJpYWJsZURlYnVn", "U25hcHNob3QibgoXQWNoaWV2ZW1lbnRzR2V0U25hcHNob3QSFwoPZ2FtZV9h", "Y2NvdW50X2lkGAEgASgNEh8KF2RlYnVnX2NvbXBsZXRlX3NuYXBzaG90GAIg", "ASgIEhkKEXNlcnZlcl90aW1lX3N0YW1wGAMgASgDIjgKHUFjaGlldmVtZW50", "c1Jlc2V0QWNoaWV2ZW1lbnRzEhcKD2dhbWVfYWNjb3VudF9pZBgBIAEoDSJD", "CidBY2hpZXZlbWVudHNVbmxvY2tlZENvbnNvbGVBY2hpZXZlbWVudHMSGAoQ", "c25vX2FjaGlldmVtZW50cxgBIAMoDyJgChRBY2hpZXZlbWVudHNTbmFwc2hv", "dBIXCg9nYW1lX2FjY291bnRfaWQYASABKA0SLwoIc25hcHNob3QYAiABKAsy",
				"HS5GZW5yaXMuQWNoaWV2ZW1lbnRzLlNuYXBzaG90IuMBChREZWJ1Z0NvbWJh", "dEFjdG9ySW5mbxIXCg9nYW1lX2FjY291bnRfaWQYASABKA0SEAoIYWNkX25h", "bWUYAiABKAkSEQoJYWN0b3Jfc25vGAMgASgPEhUKDXBsYXllcl9vcl9wZXQY", "BCABKAgSDQoFbGV2ZWwYBSABKAUSFQoNd2VhcG9uX2RhbWFnZRgGIAEoBRIU", "CgxwbGF5ZXJfYXJtb3IYByABKAUSEgoKaXRlbV9wb3dlchgIIAEoBRIOCgZt", "YXhfaHAYCSABKAISFgoObW9uc3Rlcl9yYXJpdHkYCiABKAUimAEKG0RlYnVn", "Q29tYmF0U3RhdENoYW5nZVJlYXNvbhIMCgR0eXBlGAEgASgFEhIKCmF0dHJp", "Yl9rZXkYAiABKAMSEwoLZGVzY3JpcHRpb24YAyABKAkSFAoMc2NyaXB0X3Bv", "d2VyGAQgASgPEhcKD3NjcmlwdF9jYWxsYmFjaxgFIAEoCRITCgtjb21iYXRf", "c3RhdBgGIAEoBSLTAQoVRGVidWdDb21iYXRTdGF0RGV0YWlsEg0KBXZhbHVl",
				"GAEgASgCEhQKDGZvcmNlX2VmZmVjdBgCIAEoCBIaChJuZXdfcmVwcmVzZW50", "YXRpb24YAyABKAUSEQoJb3BlcmF0aW9uGAQgASgFEj8KBnJlYXNvbhgFIAEo", "CzIvLkZlbnJpcy5HYW1lTWVzc2FnZS5EZWJ1Z0NvbWJhdFN0YXRDaGFuZ2VS", "ZWFzb24SDwoHdG9vbHRpcBgGIAEoCRIUCgx2YWx1ZV9yZXN1bHQYByABKAIi", "mAEKD0RlYnVnQ29tYmF0U3RhdBIMCgRzdGF0GAEgASgFEhoKEmNoYW5jZV9y", "b2xsX3Jlc3VsdBgCIAEoCBI6CgdkZXRhaWxzGAMgAygLMikuRmVucmlzLkdh", "bWVNZXNzYWdlLkRlYnVnQ29tYmF0U3RhdERldGFpbBIfChdhcHBsaWVzX3Rv", "X2Fub3RoZXJfc3RhdBgEIAEoCCI/ChhEZWJ1Z0hpdEVmZmVjdEZhY3Rvcklu", "Zm8SDgoGZmFjdG9yGAEgASgCEhMKC2Rlc2NyaXB0aW9uGAIgASgJIssBChhE", "ZWJ1Z0hpdEVmZmVjdENoYW5jZUluZm8SDAoEbmFtZRgBIAEoCRIRCglwb3dl",
				"cl9zbm8YAiABKA8SRAoOY2hhbmNlX2ZhY3RvcnMYAyADKAsyLC5GZW5yaXMu", "R2FtZU1lc3NhZ2UuRGVidWdIaXRFZmZlY3RGYWN0b3JJbmZvEhkKEWZpbmFs", "X3Byb2NfY2hhbmNlGAQgASgCEhcKD3JvbGxfc3VjY2Vzc2Z1bBgFIAEoCBIU", "Cgxmb3JjZV9lZmZlY3QYBiABKAUi2AEKEkRlYnVnRGFtYWdlRGV0YWlscxIe", "ChZzaGllbGRfZGFtYWdlX2Fic29yYmVkGAEgASgCEh4KFnJlbWFpbmluZ19z", "aGllbGRfdG90YWwYAiABKAISIAoYc2hpZWxkX2RhbWFnZV9tdWx0aXBsaWVy", "GAMgASgCEhYKDmVycm9yX21lc3NhZ2VzGAQgAygJEkgKEmhpdF9lZmZlY3Rf", "Y2hhbmNlcxgFIAMoCzIsLkZlbnJpcy5HYW1lTWVzc2FnZS5EZWJ1Z0hpdEVm", "ZmVjdENoYW5jZUluZm8i6gEKGURlYnVnQ29tYmF0TG9nRGFtYWdlRXZlbnQS", "HAoUZGFtYWdlX2Ftb3VudF9zY2FsZWQYASABKAISGgoSZGFtYWdlX2Ftb3Vu",
				"dF9mbGF0GAIgASgCEhMKC2RhbWFnZV90eXBlGAMgASgREhkKEWhwX3NwZWNp", "Zmllcl90eXBlGAQgASgNEiMKFGRvdF90b3RhbF9wcmVkaWN0aW9uGAUgASgI", "OgVmYWxzZRI+Cg5kYW1hZ2VfZGV0YWlscxgGIAEoCzImLkZlbnJpcy5HYW1l", "TWVzc2FnZS5EZWJ1Z0RhbWFnZURldGFpbHMilAEKF0RlYnVnQ29tYmF0TG9n", "U3RhY2tEYXRhEhUKDWNhbGxiYWNrX3R5cGUYASABKAUSEQoJcG93ZXJfc25v", "GAIgASgPEhMKC3N0YWNrX2NvdW50GAMgASgFEhYKDnBvd2VyX3Nub19mcm9t", "GAQgASgPEgwKBHRpbWUYBSABKA0SFAoMYXRfbWF4X3N0YWNrGAYgASgIInYK", "GERlYnVnQ29tYmF0TG9nU3RhY2tFdmVudBIZChFwb3dlcl9zdGFydF9wb3dl", "chgBIAEoCBI/CgpzdGFja19kYXRhGAIgAygLMisuRmVucmlzLkdhbWVNZXNz", "YWdlLkRlYnVnQ29tYmF0TG9nU3RhY2tEYXRhIloKHURlYnVnQ29tYmF0TG9n",
				"VnVsbmVyYWJsZUV2ZW50EhoKEnZ1bG5lcmFibGVfYXBwbGllZBgBIAEoCBId", "ChV2dWxuZXJhYmxlX2lzX3JlZnJlc2gYAiABKAgiZQocRGVidWdDb21iYXRM", "b2dGb3J0aWZpZWRFdmVudBIgChhmb3J0aWZpZWRfaGVhbHRoX2FwcGxpZWQY", "ASABKAISIwobZm9ydGlmaWVkX2hlYWx0aF9wb3N0X2FwcGx5GAIgASgCIkgK", "F0RlYnVnQ29tYmF0TG9nSGVhbEV2ZW50EhMKC2hlYWxfYW1vdW50GAEgASgC", "EhgKEGhlYWx0aF9wb3N0X2hlYWwYAiABKAIicQoaRGVidWdDb21iYXRMb2dT", "dGFnZ2VyRXZlbnQSGgoSbmV3X3N0YWdnZXJfYW1vdW50GAEgASgCEhwKFHRv", "dGFsX3N0YWdnZXJfYW1vdW50GAIgASgCEhkKEXN0YWdnZXJfdGhyZXNob2xk", "GAMgASgCItkFChVEZWJ1Z0NvbWJhdExvZ01lc3NhZ2USOAoGc291cmNlGAEg", "ASgLMiguRmVucmlzLkdhbWVNZXNzYWdlLkRlYnVnQ29tYmF0QWN0b3JJbmZv",
				"EjgKBnRhcmdldBgCIAEoCzIoLkZlbnJpcy5HYW1lTWVzc2FnZS5EZWJ1Z0Nv", "bWJhdEFjdG9ySW5mbxIRCglwb3dlcl9zbm8YAyABKA8SFQoNY29tbWFuZF9m", "cmFtZRgEIAEoDRIQCghwb3dlcl9pZBgFIAEoERIaChJjbGllbnRfdmlld19z", "Y2FsYXIYBiABKAISGAoQb3ZlcnBvd2VyX2NoYW5jZRgHIAEoAhJDCgxkYW1h", "Z2VfZXZlbnQYCCABKAsyLS5GZW5yaXMuR2FtZU1lc3NhZ2UuRGVidWdDb21i", "YXRMb2dEYW1hZ2VFdmVudBJLChB2dWxuZXJhYmxlX2V2ZW50GAkgASgLMjEu", "RmVucmlzLkdhbWVNZXNzYWdlLkRlYnVnQ29tYmF0TG9nVnVsbmVyYWJsZUV2", "ZW50EkkKD2ZvcnRpZmllZF9ldmVudBgKIAEoCzIwLkZlbnJpcy5HYW1lTWVz", "c2FnZS5EZWJ1Z0NvbWJhdExvZ0ZvcnRpZmllZEV2ZW50Ej8KCmhlYWxfZXZl", "bnQYCyABKAsyKy5GZW5yaXMuR2FtZU1lc3NhZ2UuRGVidWdDb21iYXRMb2dI",
				"ZWFsRXZlbnQSQQoLc3RhY2tfZXZlbnQYDCABKAsyLC5GZW5yaXMuR2FtZU1l", "c3NhZ2UuRGVidWdDb21iYXRMb2dTdGFja0V2ZW50EkUKDXN0YWdnZXJfZXZl", "bnQYDSABKAsyLi5GZW5yaXMuR2FtZU1lc3NhZ2UuRGVidWdDb21iYXRMb2dT", "dGFnZ2VyRXZlbnQSMgoFc3RhdHMYDiADKAsyIy5GZW5yaXMuR2FtZU1lc3Nh", "Z2UuRGVidWdDb21iYXRTdGF0IoACChpEZWJ1Z1RyYWNrZWRDaGVja3BvaW50", "RGF0YRIMCgRuYW1lGAEgASgJEhAKBXBvc194GAIgASgCOgEwEhAKBXBvc195", "GAMgASgCOgEwEhAKBXBvc196GAQgASgCOgEwEhEKCWlzX2FjdGl2ZRgFIAEo", "CBIXCgxwbGF5ZXJfY291bnQYBiABKA06ATASGAoNbW9uc3Rlcl9jb3VudBgH", "IAEoDToBMBIOCgNhbm4YCCABKAc6ATASDQoFYWNkaWQYCSABKAUSGgoSbW9u", "c3Rlcl9zcGF3bl9hY2RzGAogAygFEh0KFW1vbnN0ZXJfdmlzaXRpbmdfYWNk",
				"cxgLIAMoBSKHAQodRGVidWdUcmFja2VkQ2hlY2twb2ludE1lc3NhZ2USGQoR", "Y3VycmVudF93b3JsZF9zbm8YASABKAUSSwoTdHJhY2tlZF9jaGVja3BvaW50", "cxgCIAMoCzIuLkZlbnJpcy5HYW1lTWVzc2FnZS5EZWJ1Z1RyYWNrZWRDaGVj", "a3BvaW50RGF0YSL3AQopRGVidWdQbGF5ZXJUcmFja2VkQ2hlY2twb2ludFVw", "ZGF0ZU1lc3NhZ2USEAoFcG9zX3gYASABKAI6ATASEAoFcG9zX3kYAiABKAI6", "ATASEAoFcG9zX3oYAyABKAI6ATASGQoOY2hlY2twb2ludF9hbm4YBCABKAc6", "ATASKAogY2hlY2twb2ludF9oYXNfcG9zaXRpb25fb3ZlcnJpZGUYBSABKAgS", "IAoYdHJhY2tlZF9jaGVja3BvaW50X2NvdW50GAYgASgFEi0KJXBsYXllcl9t", "b3N0X3JlY2VudF9jaGVja3BvaW50X2luZGljZXMYByADKAUiVQoURGVidWdE", "dW1wSGVyb01lc3NhZ2USDAoEbmFtZRgBIAEoCRIvCgloZXJvX2RhdGEYAiAB",
				"KAsyHC5GZW5yaXMuSGVyby5TYXZlZERlZmluaXRpb24idQoSRGVidWdMb290", "QWN0b3JJbmZvEhcKD2dhbWVfYWNjb3VudF9pZBgBIAEoDRIQCghhY2RfbmFt", "ZRgCIAEoCRIRCglhY3Rvcl9zbm8YAyABKA8SDQoFbGV2ZWwYBCABKAUSEgoK", "d29ybGRfdGllchgFIAEoBSJfChREZWJ1Z0xvb3RWYWx1ZVJlY29yZBISCgpk", "YXRhX2Zsb2F0GAEgASgCEhAKCGRhdGFfaW50GAIgASgFEhEKCW9wZXJhdGlv", "bhgDIAEoBRIOCgZyZWFzb24YBCABKAki/QEKFERlYnVnTG9vdEVudHJ5UmVz", "dWx0EhEKCW91dHB1dF9pZBgBIAEoDRINCgVmbGFncxgCIAEoBRIMCgRyb2xs", "GAMgASgCEhQKDGZpbmFsX2NoYW5jZRgEIAEoAhJACg5jaGFuY2VfaGlzdG9y", "eRgFIAMoCzIoLkZlbnJpcy5HYW1lTWVzc2FnZS5EZWJ1Z0xvb3RWYWx1ZVJl", "Y29yZBIUCgxuZXh0X25vZGVfaWQYBiABKA0SEAoIaXRlbV9zbm8YByABKA8S",
				"FwoPY3VycmVuY3lfYW1vdW50GAggASgFEhwKFGZhaWxlZF9jb25kaXRpb25f", "c25vGAkgASgPIvQBChJEZWJ1Z0xvb3RFbnRyeUluZm8SDQoFZmxhZ3MYASAB", "KAUSEAoIcXVhbnRpdHkYAiABKAUSDAoEcm9sbBgDIAEoAhIUCgxmaW5hbF9j", "aGFuY2UYBCABKAISQAoOY2hhbmNlX2hpc3RvcnkYBSADKAsyKC5GZW5yaXMu", "R2FtZU1lc3NhZ2UuRGVidWdMb290VmFsdWVSZWNvcmQSOQoHcmVzdWx0cxgG", "IAMoCzIoLkZlbnJpcy5HYW1lTWVzc2FnZS5EZWJ1Z0xvb3RFbnRyeVJlc3Vs", "dBIcChRmYWlsZWRfY29uZGl0aW9uX3NubxgHIAEoDyK7AQoURGVidWdMb290", "Tm9kZU1lc3NhZ2USDwoHbm9kZV9pZBgBIAEoDRIWCg5ub2RlX2lkX3BhcmVu", "dBgCIAEoDRIaChJ0cmVhc3VyZV9jbGFzc19zbm8YAyABKA8SEwoLY2hvb3Nl", "X3R5cGUYBCABKAUSOgoKZW50cnlfaW5mbxgFIAMoCzImLkZlbnJpcy5HYW1l",
				"TWVzc2FnZS5EZWJ1Z0xvb3RFbnRyeUluZm8SDQoFZmxhZ3MYBiABKAUieQoX", "RGVidWdMb290UmFuZG9tUm9sbEluZm8SDgoGY2hhbmNlGAEgASgCEgwKBHJv", "bGwYAiABKAISQAoOY2hhbmNlX2hpc3RvcnkYAyADKAsyKC5GZW5yaXMuR2Ft", "ZU1lc3NhZ2UuRGVidWdMb290VmFsdWVSZWNvcmQingEKHERlYnVnTG9vdE91", "dHB1dFVwZGF0ZU1lc3NhZ2USEQoJb3V0cHV0X2lkGAEgASgNEhMKCGl0ZW1f", "YW5uGAIgASgHOgEwEhEKCWxldmVsX3JlcRgDIAEoBRJDChFsZXZlbF9yZXFf", "aGlzdG9yeRgEIAMoCzIoLkZlbnJpcy5HYW1lTWVzc2FnZS5EZWJ1Z0xvb3RW", "YWx1ZVJlY29yZCKCBAoWRGVidWdMb290T3V0cHV0TWVzc2FnZRIRCglvdXRw", "dXRfaWQYASABKA0SEAoIaXRlbV9zbm8YAiABKA8SDwoHcXVhbGl0eRgDIAEo", "BRIRCglsZXZlbF9yZXEYBCABKAUSQwoRbGV2ZWxfcmVxX2hpc3RvcnkYBSAD",
				"KAsyKC5GZW5yaXMuR2FtZU1lc3NhZ2UuRGVidWdMb290VmFsdWVSZWNvcmQS", "GAoQcXVhbGl0eV9tb2RpZmllchgGIAEoBRJACgtzYWNyZWRfcm9sbBgHIAEo", "CzIrLkZlbnJpcy5HYW1lTWVzc2FnZS5EZWJ1Z0xvb3RSYW5kb21Sb2xsSW5m", "bxJDCg5hbmNlc3RyYWxfcm9sbBgIIAEoCzIrLkZlbnJpcy5HYW1lTWVzc2Fn", "ZS5EZWJ1Z0xvb3RSYW5kb21Sb2xsSW5mbxINCgV2YWx1ZRgJIAEoBRI/Cg12", "YWx1ZV9oaXN0b3J5GAogAygLMiguRmVucmlzLkdhbWVNZXNzYWdlLkRlYnVn", "TG9vdFZhbHVlUmVjb3JkEhUKDWN1cnJlbmN5X3R5cGUYCyABKAUSDwoHc29j", "a2V0cxgMIAEoBRJBCg9zb2NrZXRzX2hpc3RvcnkYDSADKAsyKC5GZW5yaXMu", "R2FtZU1lc3NhZ2UuRGVidWdMb290VmFsdWVSZWNvcmQirAEKGERlYnVnTG9v", "dEluc3RhbmNlTWVzc2FnZRITCgtpbnN0YW5jZV9pZBgBIAEoDRILCgNlbmQY",
				"AiABKAgSNgoGbG9vdGVyGAMgASgLMiYuRmVucmlzLkdhbWVNZXNzYWdlLkRl", "YnVnTG9vdEFjdG9ySW5mbxI2CgZsb290ZWUYBCABKAsyJi5GZW5yaXMuR2Ft", "ZU1lc3NhZ2UuRGVidWdMb290QWN0b3JJbmZvIqwBChNHYW1lU3luY0RhdGFN", "ZXNzYWdlEhkKEWdhbWVfc3luY2VkX2ZsYWdzGAEgASgNEhMKC3N1YnpvbmVf", "c25vGAIgASgPEhsKE3JhbmRvbV93ZWF0aGVyX3NlZWQYAyABKBESEgoKd29y", "bGRfdGllchgEIAEoERI0Cg1kZXNpZ25lcl92YXJzGAUgAygLMh0uRmVucmlz", "Lkhlcm8uRGVzaWduZXJWYXJpYWJsZSpACh5Qcm9ncmVzc0RpYWJsb0VuZENv", "bmRpdGlvblR5cGUSDQoJUlVOX0NPVU5UEAASDwoLUkVBQ0hfTEVWRUwQAQ=="
			}));
			GameMessageReflection.descriptor = FileDescriptor.FromGeneratedCode(array, new FileDescriptor[]
			{
				HeroReflection.Descriptor,
				ItemsReflection.Descriptor,
				AchievementsReflection.Descriptor,
				OnlineReflection.Descriptor
			}, new GeneratedClrTypeInfo(new Type[] { typeof(ProgressDiabloEndConditionType) }, null, new GeneratedClrTypeInfo[]
			{
				new GeneratedClrTypeInfo(typeof(TutorialMessage), TutorialMessage.Parser, new string[] { "TutorialSno", "UiAnchorName", "ActorId" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(InitialLoginDataRequest), InitialLoginDataRequest.Parser, new string[] { "CountryIdFourcc" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(InitialLoginDataQueuedResponse), InitialLoginDataQueuedResponse.Parser, new string[] { "ServiceId", "TimeoutTickInterval" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(CancelLoginDataRequest), CancelLoginDataRequest.Parser, null, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(StartGameTransfer), StartGameTransfer.Parser, new string[] { "GameId", "GameAddress", "GamePort", "Player", "GameSubzoneSno", "TriggerFade" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(MailContents), MailContents.Parser, new string[] { "AppendMessages", "Mails" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(PlayerCommand), PlayerCommand.Parser, new string[] { "MCommandFrame", "MYaw", "MThrottleX", "MThrottleY", "MInputFlags", "MTeleportIndex", "MDestinationX", "MDestinationY", "MDestinationZ" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(PhysicsMovementStateMessage), PhysicsMovementStateMessage.Parser, new string[]
				{
					"MAnn", "MIsDelta", "MIsTargetState", "MFlags", "MCommandFrame", "MTeleportIndex", "MWorldLocationX", "MWorldLocationY", "MWorldLocationZ", "MVelocityX",
					"MVelocityY", "MVelocityZ", "MVelFromGravX", "MVelFromGravY", "MVelFromGravZ", "MAnimImpulseX", "MAnimImpulseY", "MAnimImpulseZ", "MForcesX", "MForcesY",
					"MForcesZ", "MYaw", "MDesiredYaw", "MYawSpeed", "MSpeed", "MAnimationScalingTimeScale", "MCurrentMotionIsAnimationDriven", "MSnoPowerAnimKeyOverride", "MPrevCommandFrame"
				}, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(PolygonRegionPoint), PolygonRegionPoint.Parser, new string[] { "PosX", "PosY" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(PolygonRegion), PolygonRegion.Parser, new string[] { "CenterPosX", "CenterPosY", "Points" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(MinimapMarkerInfoMessage), MinimapMarkerInfoMessage.Parser, new string[]
				{
					"GameAccountId", "IdPing", "PosX", "PosY", "PosZ", "IdSworld", "SnoWorld", "SnoLevelArea", "ImageHandle", "SnoStringList",
					"StringLabelHandle", "Active", "RespectsFogOfWar", "RespectsExploredArea", "IsPing", "UsesAreaRadius", "FromBakedData", "IsDebugPing", "MaxDisplayRangeSq", "DiscoverRangeSq",
					"QuestAreaRadius", "SnoQuestSource", "QuestPhaseUid", "QuestCallbackUid", "ServerMarkerType", "SnoDestWorld", "PolygonRegion"
				}, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(ZoneProgressRewardData), ZoneProgressRewardData.Parser, new string[] { "RewardType", "SnoItemReward", "SnoTrackedReward", "GoldTier", "StaticGoldAmount" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(ZoneProgressRewardPerTierData), ZoneProgressRewardPerTierData.Parser, new string[] { "Rewards", "StaticXpReward", "XpTier" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(ZoneProgressPerZoneGlobalData), ZoneProgressPerZoneGlobalData.Parser, new string[] { "SnoCamps", "SnoDungeons", "SnoFogOfWar", "SnoSideQuests", "SnoWaypoints", "GbidHiddenCaches", "RewardsPerTier" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(ZoneProgressWorldToDPOData), ZoneProgressWorldToDPOData.Parser, new string[] { "SnoWorld", "SnoDungeonQuests" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(ZoneProgressGlobalDataMessage), ZoneProgressGlobalDataMessage.Parser, new string[] { "PerZoneData", "RenownPerProgressType", "RenownPerRewardThreshold", "RewardStringHandles", "TrackedRewardStringHandles", "WorldToDpoMap" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugWorldPlace), DebugWorldPlace.Parser, new string[] { "WorldSno", "PosX", "PosY", "PosZ" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugTarget), DebugTarget.Parser, new string[] { "AcdName", "WorldPlace", "Pathable", "TimeSincePathable" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(ProgressDiabloEventLoot), ProgressDiabloEventLoot.Parser, new string[] { "Item", "Equipped", "TreasureClassSno" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(ProgressDiabloEventCurrency), ProgressDiabloEventCurrency.Parser, new string[] { "CurrencyType", "CurrencyAmount" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(ProgressDiabloEvent), ProgressDiabloEvent.Parser, new string[]
				{
					"ActorSno", "LevelAreaSno", "MonsterCombatItemPower", "PlayerCombatItemPower", "Loot", "ExperienceGained", "MonsterRarity", "PlayerLevel", "MonsterLevel", "PlayerLevelProgress",
					"ItemQualityCounts", "PlayerLootItemPower", "PlayerAttackRatingFromItems", "PlayerDefenseRatingFromItems", "PlayerAttackDefenseLevelBonus", "PlayerAttackRatingTotal", "PlayerDefenseRatingTotal", "ExperienceTotal", "GoldFromVendoredItemsTotal", "GoldFromLootTotal",
					"Currency"
				}, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(ProgressDiabloUpdate), ProgressDiabloUpdate.Parser, new string[] { "Events", "CompletedRunCount" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(ProgressDiabloRequest), ProgressDiabloRequest.Parser, new string[] { "EndConditionType", "RunGoal", "LevelGoal" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AIDebugVariable), AIDebugVariable.Parser, new string[] { "Name", "NameHash", "Value", "TicksUntilExpiration", "SourceAibehaviorSno" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AIStateDebugSnapshotEntryCondition), AIStateDebugSnapshotEntryCondition.Parser, new string[] { "Name", "Evaluated", "Failed", "Result", "Enabled" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AIStateDebugSnapshotEntry), AIStateDebugSnapshotEntry.Parser, new string[]
				{
					"Name", "PowerSno", "PowerTargetName", "AistateSwitchName", "AistateSwitchNameHash", "StartConditions", "InterruptConditions", "CooldownTicksRemaining", "IsCurrentPrimary", "Evaluated",
					"Failed", "Selected", "PowerFailureReasonsString", "CooldownKey", "Enabled", "EvaluationOrder", "Weight", "TargetAnn", "TargetWorldPlace", "VariantMismatch"
				}, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AIStateDebugSnapshotCurrentPower), AIStateDebugSnapshotCurrentPower.Parser, new string[] { "PowerSno", "OriginalPowerSno", "Target", "TicksExecuting" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AIStateDebugSnapshotRetreat), AIStateDebugSnapshotRetreat.Parser, new string[] { "RetreatRadius", "TetherTypeName", "Retreating" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AIVariableDebugSnapshot), AIVariableDebugSnapshot.Parser, new string[] { "LocalVariables", "RemoteVariables" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AIStateDebugSnapshot), AIStateDebugSnapshot.Parser, new string[]
				{
					"Ann", "CommandFrame", "WorldPlace", "Yaw", "CurrentPower", "PrimaryAistateName", "TicksInPrimaryAistate", "QueuedAistateSwitchName", "Entries", "MergedAistateNames",
					"HostileTargets", "FriendlyTargets", "AipropTargets", "CurrentAibehaviorName", "VariableSnapshot", "QueuedAistateSwitchTicksRemaining", "QueuedAistateSwitchEntryIndex", "CachedTargets", "ForcedCooldownKey", "ForcedCooldown",
					"ChosenWeight"
				}, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AIStateDebugRealTimeSnapshot), AIStateDebugRealTimeSnapshot.Parser, new string[] { "Ann", "CommandFrame", "VariableSnapshot" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AchievementsGetSnapshot), AchievementsGetSnapshot.Parser, new string[] { "GameAccountId", "DebugCompleteSnapshot", "ServerTimeStamp" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AchievementsResetAchievements), AchievementsResetAchievements.Parser, new string[] { "GameAccountId" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AchievementsUnlockedConsoleAchievements), AchievementsUnlockedConsoleAchievements.Parser, new string[] { "SnoAchievements" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(AchievementsSnapshot), AchievementsSnapshot.Parser, new string[] { "GameAccountId", "Snapshot" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugCombatActorInfo), DebugCombatActorInfo.Parser, new string[] { "GameAccountId", "AcdName", "ActorSno", "PlayerOrPet", "Level", "WeaponDamage", "PlayerArmor", "ItemPower", "MaxHp", "MonsterRarity" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugCombatStatChangeReason), DebugCombatStatChangeReason.Parser, new string[] { "Type", "AttribKey", "Description", "ScriptPower", "ScriptCallback", "CombatStat" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugCombatStatDetail), DebugCombatStatDetail.Parser, new string[] { "Value", "ForceEffect", "NewRepresentation", "Operation", "Reason", "Tooltip", "ValueResult" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugCombatStat), DebugCombatStat.Parser, new string[] { "Stat", "ChanceRollResult", "Details", "AppliesToAnotherStat" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugHitEffectFactorInfo), DebugHitEffectFactorInfo.Parser, new string[] { "Factor", "Description" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugHitEffectChanceInfo), DebugHitEffectChanceInfo.Parser, new string[] { "Name", "PowerSno", "ChanceFactors", "FinalProcChance", "RollSuccessful", "ForceEffect" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugDamageDetails), DebugDamageDetails.Parser, new string[] { "ShieldDamageAbsorbed", "RemainingShieldTotal", "ShieldDamageMultiplier", "ErrorMessages", "HitEffectChances" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugCombatLogDamageEvent), DebugCombatLogDamageEvent.Parser, new string[] { "DamageAmountScaled", "DamageAmountFlat", "DamageType", "HpSpecifierType", "DotTotalPrediction", "DamageDetails" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugCombatLogStackData), DebugCombatLogStackData.Parser, new string[] { "CallbackType", "PowerSno", "StackCount", "PowerSnoFrom", "Time", "AtMaxStack" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugCombatLogStackEvent), DebugCombatLogStackEvent.Parser, new string[] { "PowerStartPower", "StackData" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugCombatLogVulnerableEvent), DebugCombatLogVulnerableEvent.Parser, new string[] { "VulnerableApplied", "VulnerableIsRefresh" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugCombatLogFortifiedEvent), DebugCombatLogFortifiedEvent.Parser, new string[] { "FortifiedHealthApplied", "FortifiedHealthPostApply" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugCombatLogHealEvent), DebugCombatLogHealEvent.Parser, new string[] { "HealAmount", "HealthPostHeal" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugCombatLogStaggerEvent), DebugCombatLogStaggerEvent.Parser, new string[] { "NewStaggerAmount", "TotalStaggerAmount", "StaggerThreshold" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugCombatLogMessage), DebugCombatLogMessage.Parser, new string[]
				{
					"Source", "Target", "PowerSno", "CommandFrame", "PowerId", "ClientViewScalar", "OverpowerChance", "DamageEvent", "VulnerableEvent", "FortifiedEvent",
					"HealEvent", "StackEvent", "StaggerEvent", "Stats"
				}, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugTrackedCheckpointData), DebugTrackedCheckpointData.Parser, new string[]
				{
					"Name", "PosX", "PosY", "PosZ", "IsActive", "PlayerCount", "MonsterCount", "Ann", "Acdid", "MonsterSpawnAcds",
					"MonsterVisitingAcds"
				}, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugTrackedCheckpointMessage), DebugTrackedCheckpointMessage.Parser, new string[] { "CurrentWorldSno", "TrackedCheckpoints" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugPlayerTrackedCheckpointUpdateMessage), DebugPlayerTrackedCheckpointUpdateMessage.Parser, new string[] { "PosX", "PosY", "PosZ", "CheckpointAnn", "CheckpointHasPositionOverride", "TrackedCheckpointCount", "PlayerMostRecentCheckpointIndices" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugDumpHeroMessage), DebugDumpHeroMessage.Parser, new string[] { "Name", "HeroData" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugLootActorInfo), DebugLootActorInfo.Parser, new string[] { "GameAccountId", "AcdName", "ActorSno", "Level", "WorldTier" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugLootValueRecord), DebugLootValueRecord.Parser, new string[] { "DataFloat", "DataInt", "Operation", "Reason" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugLootEntryResult), DebugLootEntryResult.Parser, new string[] { "OutputId", "Flags", "Roll", "FinalChance", "ChanceHistory", "NextNodeId", "ItemSno", "CurrencyAmount", "FailedConditionSno" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugLootEntryInfo), DebugLootEntryInfo.Parser, new string[] { "Flags", "Quantity", "Roll", "FinalChance", "ChanceHistory", "Results", "FailedConditionSno" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugLootNodeMessage), DebugLootNodeMessage.Parser, new string[] { "NodeId", "NodeIdParent", "TreasureClassSno", "ChooseType", "EntryInfo", "Flags" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugLootRandomRollInfo), DebugLootRandomRollInfo.Parser, new string[] { "Chance", "Roll", "ChanceHistory" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugLootOutputUpdateMessage), DebugLootOutputUpdateMessage.Parser, new string[] { "OutputId", "ItemAnn", "LevelReq", "LevelReqHistory" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugLootOutputMessage), DebugLootOutputMessage.Parser, new string[]
				{
					"OutputId", "ItemSno", "Quality", "LevelReq", "LevelReqHistory", "QualityModifier", "SacredRoll", "AncestralRoll", "Value", "ValueHistory",
					"CurrencyType", "Sockets", "SocketsHistory"
				}, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(DebugLootInstanceMessage), DebugLootInstanceMessage.Parser, new string[] { "InstanceId", "End", "Looter", "Lootee" }, null, null, null, null),
				new GeneratedClrTypeInfo(typeof(GameSyncDataMessage), GameSyncDataMessage.Parser, new string[] { "GameSyncedFlags", "SubzoneSno", "RandomWeatherSeed", "WorldTier", "DesignerVars" }, null, null, null, null)
			}));
		}

		// Token: 0x040014ED RID: 5357
		private static FileDescriptor descriptor;
	}
}
